
export type Molecule = {
  name: string;
  smiles: string;
  formula: string;
};

export const molecules: Molecule[] = [
    { name: 'Aspirin', smiles: 'CC(=O)Oc1ccccc1C(=O)O', formula: 'C9H8O4' },
    { name: 'Ibuprofen', smiles: 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O', formula: 'C13H18O2' },
    { name: 'Paracetamol', smiles: 'CC(=O)NC1=CC=C(O)C=C1', formula: 'C8H9NO2' },
    { name: 'Caffeine', smiles: 'CN1C=NC2=C1C(=O)N(C(=O)N2C)C', formula: 'C8H10N4O2' },
    { name: 'Metformin', smiles: 'CN(C)C(=N)N=C(N)N', formula: 'C4H11N5' },
    { name: 'Amoxicillin', smiles: 'CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(O)C=C3)N)C(=O)O)C', formula: 'C16H19N3O5S' },
    { name: 'Diazepam (Valium)', smiles: 'CN1C2=C(C=C(C=C2)Cl)C(=NC1=O)C3=CC=CC=C3', formula: 'C16H13ClN2O' },
    { name: 'Sertraline (Zoloft)', smiles: 'CN[C@H]1CC[C@@H](C2=CC=CC=C12)C3=CC(=C(C=C3)Cl)Cl', formula: 'C17H17Cl2N' },
    { name: 'Lisinopril', smiles: 'C[C@H](N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCCN)C(=O)O', formula: 'C21H31N3O5' },
    { name: 'Atorvastatin (Lipitor)', smiles: 'CC(C)c1c(c(n(c1c2ccc(cc2)F)C(C)C)CC[C@H](C[C@H](CC(=O)O)O)O)c3ccccc3', formula: 'C33H35FN2O5' },
    { name: 'Imatinib (Gleevec)', smiles: 'Cc1ccc(cc1)c2cc(c(cn2)Nc3ncc(c(n3)C)-c4cccc(c4)C(F)(F)F)C(=O)N5CCN(CC5)C', formula: 'C29H31F3N7O' },
    { name: 'Penicillin G', smiles: 'CC1(C(N2C(S1)C(C2=O)NC(=O)Cc3ccccc3)C(=O)O)C', formula: 'C16H18N2O4S' },
    { name: 'Ciprofloxacin', smiles: 'C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O', formula: 'C17H18FN3O3' },
    { name: 'Warfarin', smiles: 'CC(=O)CC(C1=C(C=CC=C1)O)C2=C(C(=O)OC3=CC=CC=C23)O', formula: 'C19H16O4' },
    { name: 'Theophylline', smiles: 'CN1C=NC2=C1C(=O)NC(=O)N2C', formula: 'C7H8N4O2' },
    { name: 'Dopamine', smiles: 'C1=CC(=C(C=C1CCN)O)O', formula: 'C8H11NO2' },
    { name: 'Serotonin', smiles: 'C1=CC=C2C(=C1)C(=CN2)CCN', formula: 'C10H12N2O' },
    { name: 'Adrenaline (Epinephrine)', smiles: 'CNC[C@H](C1=CC(=C(C=C1)O)O)O', formula: 'C9H13NO3' },
    { name: 'Glucose', smiles: 'C(C1C(C(C(C(O1)O)O)O)O)O)O', formula: 'C6H12O6' },
    { name: 'Fructose', smiles: 'C(C1C(C(C(O1)(CO)O)O)O)O', formula: 'C6H12O6' },
    { name: 'Sucrose', smiles: 'C(C1C(C(C(C(O1)O)O)O)O)OC2(C(C(C(O2)CO)O)O)CO', formula: 'C12H22O11' },
    { name: 'Cholesterol', smiles: 'CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C', formula: 'C27H46O' },
    { name: 'Testosterone', smiles: 'C[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C', formula: 'C19H28O2' },
    { name: 'Estradiol', smiles: 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O', formula: 'C18H24O2' },
    { name: 'Benzene', smiles: 'c1ccccc1', formula: 'C6H6' },
    { name: 'Ethanol', smiles: 'CCO', formula: 'C2H6O' },
    { name: 'Methanol', smiles: 'CO', formula: 'CH4O'},
    { name: 'Glycerol', smiles: 'C(C(CO)O)O', formula: 'C3H8O3'},
    { name: 'Acetone', smiles: 'CC(=O)C', formula: 'C3H6O'},
    { name: 'Formaldehyde', smiles: 'C=O', formula: 'CH2O'},
    { name: 'Urea', smiles: 'C(=O)(N)N', formula: 'CH4N2O'},
    { name: 'Glycine', smiles: 'C(C(=O)O)N', formula: 'C2H5NO2' },
    { name: 'Alanine', smiles: 'C[C@H](C(=O)O)N', formula: 'C3H7NO2' },
    { name: 'Valine', smiles: 'CC(C)[C@H](C(=O)O)N', formula: 'C5H11NO2' },
    { name: 'Leucine', smiles: 'CC(C)C[C@H](C(=O)O)N', formula: 'C6H13NO2' },
    { name: 'Isoleucine', smiles: 'CC[C@H](C)[C@H](C(=O)O)N', formula: 'C6H13NO2' },
    { name: 'Proline', smiles: 'C1CC(NC1)C(=O)O', formula: 'C5H9NO2' },
    { name: 'Phenylalanine', smiles: 'c1ccc(cc1)C[C@H](C(=O)O)N', formula: 'C9H11NO2' },
    { name: 'Tryptophan', smiles: 'c1ccc2c(c1)c(c[nH]2)C[C@H](C(=O)O)N', formula: 'C11H12N2O2' },
    { name: 'Tyrosine', smiles: 'c1cc(ccc1C[C@H](C(=O)O)N)O', formula: 'C9H11NO3' },
    { name: 'Aspartic Acid', smiles: 'C([C@H](C(=O)O)N)C(=O)O', formula: 'C4H7NO4' },
    { name: 'Glutamic Acid', smiles: 'C(CC(=O)O)[C@H](C(=O)O)N', formula: 'C5H9NO4' },
    { name: 'Asparagine', smiles: 'C([C@H](C(=O)O)N)C(=O)N', formula: 'C4H8N2O3' },
    { name: 'Glutamine', smiles: 'C(CC(=O)N)[C@H](C(=O)O)N', formula: 'C5H10N2O3' },
    { name: 'Histidine', smiles: 'c1c[nH]c(n1)C[C@H](C(=O)O)N', formula: 'C6H9N3O2' },
    { name: 'Lysine', smiles: 'C(C[C@H](C(=O)O)N)CCN', formula: 'C6H14N2O2' },
    { name: 'Arginine', smiles: 'C(C[C@H](C(=O)O)N)CN=C(N)N', formula: 'C6H14N4O2' },
    { name: 'Serine', smiles: 'C([C@H](C(=O)O)N)O', formula: 'C3H7NO3' },
    { name: 'Threonine', smiles: 'C[C@H]([C@H](C(=O)O)N)O', formula: 'C4H9NO3' },
    { name: 'Cysteine', smiles: 'C([C@H](C(=O)O)N)S', formula: 'C3H7NO2S' },
    { name: 'Methionine', smiles: 'CSCC[C@H](C(=O)O)N', formula: 'C5H11NO2S' },
    { name: 'Guanine', smiles: 'c1nc2c(n1C3C(C(C(O3)CO)O)O)n[nH]c2N', formula: 'C10H13N5O5' },
    { name: 'Adenine', smiles: 'c1nc(c2c(n1)n(cn2)C3C(C(C(O3)CO)O)O)N', formula: 'C10H13N5O4' },
    { name: 'Thymine', smiles: 'Cc1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)O)O', formula: 'C10H14N2O6' },
    { name: 'Cytosine', smiles: 'c1cn(c(=O)n(c1)N)C2C(C(C(O2)CO)O)O', formula: 'C9H13N3O5' },
    { name: 'Uracil', smiles: 'c1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)O)O', formula: 'C9H12N2O6' },
    { name: 'Melatonin', smiles: 'CC(=O)NCc1ccc2c(c1)c(c[nH]2)OC', formula: 'C13H16N2O2' },
    { name: 'Gabapentin', smiles: 'C1CCC(CC1)(CC(=O)O)CN', formula: 'C9H17NO2' },
    { name: 'Pregabalin', smiles: 'CC(C)C[C@H](CC(=O)O)CN', formula: 'C8H17NO2' },
    { name: 'Omeprazole', smiles: 'Cc1c(c(nc(n1)C)OC)CS(=O)c2[nH]c3cc(c(cc3n2)OC)C', formula: 'C17H19N3O3S' },
    { name: 'Loratadine', smiles: 'c1ccc(c(c1)Cl)C2(C(=O)N(C=C2)C(=O)OCC)c3cc[nH]n3', formula: 'C22H23ClN2O2' },
    { name: 'Cetirizine', smiles: 'c1ccc(cc1)C(c2ccccc2)N3CCN(CC3)CCOCC(=O)O', formula: 'C21H25ClN2O3' },
    { name: 'Fexofenadine', smiles: 'c1ccc(cc1)C(O)(CCCC(O)(C(=O)O)C(C)C)c2ccccc2', formula: 'C32H39NO4' },
    { name: 'Ranitidine', smiles: 'CN(C)CSCC/C=C(\\N=C/N)/[N+](=O)[O-]', formula: 'C13H22N4O3S' },
    { name: 'Cimetidine', smiles: 'CN=C(N)NCCCSc1cn(c(n1)C)C', formula: 'C10H16N6S' },
    { name: 'Famotidine', smiles: 'c1csc(c1)CSCCN=C(N)N=S(=O)(N)N', formula: 'C8H15N7O2S3' },
    { name: 'Ondansetron', smiles: 'Cc1[nH]c2c(c1)c(c(=O)n2CC3C(C(C(C3)C)C)C)C', formula: 'C18H19N3O' },
    { name: 'Acyclovir', smiles: 'c1nc(c2c(n1)n(cn2)COCCO)N', formula: 'C8H11N5O3' },
    { name: 'Valacyclovir', smiles: 'CC(C)C(=O)O[C@H](C)c1ccc(cc1)c2ccccc2', formula: 'C13H20N6O4' },
    { name: 'Zidovudine (AZT)', smiles: 'c1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)N=[N+]=[N-])O', formula: 'C10H13N5O4' },
    { name: 'Efavirenz', smiles: 'c1cc(c(cc1C(F)(F)F)C#CC2(C(=O)NC(=O)N2)c3cyclopropyl)Cl', formula: 'C14H9ClF3N2O2' },
    { name: 'Nevirapine', smiles: 'c1ccc2c(c1)c(nc(n2)c3cc(c(c(c3)C)C)C)N', formula: 'C15H14N4' },
    { name: 'Ritonavir', smiles: 'CC(C)c1nc(sc1)CNC(=O)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@@H]([C@H](C)C)O', formula: 'C37H48N6O5S2' },
    { name: 'Lopinavir', smiles: 'CC(C)c1nc(sc1)CNC(=O)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@@H]([C@H](C)C)O', formula: 'C37H48N6O5S2' },
    { name: 'Saquinavir', smiles: 'CC(C)(C)NC(=O)[C@H]1C[C@H]([C@@H](C1)O)N2C[C@H](C[C@H]2C(=O)N[C@@H](Cc3ccccc3)C[C@H]4CC[C@H]([C@@H]4)N)O', formula: 'C38H50N6O5' },
    { name: 'Indinavir', smiles: 'CC(C)(C)NC(=O)[C@H]1C[C@H]([C@@H](C1)O)N2C[C@H](C[C@H]2C(=O)N[C@@H](Cc3ccccc3)C[C@H]4CC[C@H]([C@@H]4)N)O', formula: 'C36H47N5O4' },
    { name: 'Nelfinavir', smiles: 'c1ccc(cc1)CS(=O)(=O)N[C@@H]2C[C@H]([C@@H]([C@H](C2)O)N(C)C(=O)N[C@@H](Cc3ccccc3)C[C@H]4CC[C@H]([C@@H]4)N)O', formula: 'C32H45N3O4S' },
    { name: 'Amprenavir', smiles: 'c1ccc(cc1)S(=O)(=O)N[C@H]2CCOC2', formula: 'C25H35N3O6S' },
    { name: 'Fosamprenavir', smiles: 'c1ccc(cc1)S(=O)(=O)N[C@H]2CCOC2.OP(=O)(O)O', formula: 'C25H36N3O9PS' },
    { name: 'Tipranavir', smiles: 'CC(C)c1cc(c(c(c1)S(=O)(=O)N)C(C)C)C(=O)N[C@H](Cc2ccccc2)c3cc(c(c(c3)C)C)C', formula: 'C31H33F2N3O5S' },
    { name: 'Darunavir', smiles: 'CC(C)c1nc(sc1)COC(=O)N[C@H](Cc2ccccc2)[C@H]([C@H](O)[C@@H]3CCCN3C(=O)C(C)(C)C)O', formula: 'C27H37N3O7S' },
    { name: 'Atazanavir', smiles: 'CC(C)(C)NC(=O)[C@H](c1ccccc1)N(C)C(=O)N[C@@H](Cc2ccccc2)[C@@H]([C@H](O)c3ccc(cc3)C(=O)N(C)C)O', formula: 'C38H52N6O7' },
    { name: 'Cobicistat', smiles: 'CC(C)N(C(=O)N[C@H](Cc1ccccc1)C[C@H](c2ccccc2)N(C)C(=O)N3C[C@H](C[C@H]3c4cncs4)C(C)(C)C)C', formula: 'C40H53N7O5S2' },
    { name: 'Dolutegravir', smiles: 'c1c(c(c(c(c1F)F)C(=O)N)C(=O)O)C(=O)NCC2COC(O2)c3cc(c(cc3F)F)F', formula: 'C20H19F2N3O5' },
    { name: 'Elvitegravir', smiles: 'c1c(c(c(c(c1)OC)C(=O)N)C(=O)O)C(=O)Cc2cc(c(cc2Cl)OC)OC', formula: 'C23H23ClNO7' },
    { name: 'Raltegravir', smiles: 'c1c(c(c(c(c1)F)C(=O)N)C(=O)O)C(=O)NCc2c(c(c(=O)[nH]c2=O)N)C(C)C', formula: 'C20H21FN6O5' },
    { name: 'Bictegravir', smiles: 'c1c(c(c(c(c1)F)C(=O)N)C(=O)O)C(=O)NCc2c(c(c(nc2F)C)C)C', formula: 'C21H21F3N3O5' },
    { name: 'Maraviroc', smiles: 'CC(C)N1CC(C(C1)(c2ccc(cc2)F)c3ccccc3)N4C[C@@H](C[C@@H]4C(=O)N)c5cn(c(n5)C)C', formula: 'C29H41F2N5O' },
    { name: 'Enfuvirtide', smiles: 'Ac-YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF-NH2', formula: 'C204H301N51O64' },
    { name: 'Sofosbuvir', smiles: 'C[C@H](C(=O)O[C@H]1C[C@H]([C@@H]([C@H]1C)F)n2ccc(nc2)C(=O)N)P(=O)(O)Oc3ccccc3', formula: 'C22H29FN3O9P' },
    { name: 'Ledipasvir', smiles: 'c1cc(ccc1C2=C[C@H]3N(C2=O)[C@@H](C(=O)N[C@H](C(=O)O)C(C)C)C[C@H]3c4ccc(cc4)c5ccccc5)c6nc7c(c(n6)C)c(c(c(c7)C)C)C', formula: 'C49H54F2N8O6' },
    { name: 'Dasabuvir', smiles: 'c1c(c(c(c(c1)OC)C(=O)N)C(=O)O)c2ccc(cc2)S(=O)(=O)NC(C)C', formula: 'C26H27N3O5S' },
    { name: 'Ombitasvir', smiles: 'CC(C)c1nc(sc1)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@H]([C@@H](C)C)Oc4ccc(cc4)C(=O)N(C)C', formula: 'C50H67N7O5S2' },
    { name: 'Paritaprevir', smiles: 'CC(C)c1nc(sc1)C(=O)N[C@H](C[C@H]2CCNC2=O)[C@H](c3cyclopropyl)C(=O)N[C@H](C(=O)N4C[C@H](C[C@H]4c5cncs5)C(C)(C)C)C(C)C', formula: 'C48H61N7O8S2' },
    { name: 'Glecaprevir', smiles: 'CC(C)c1nc(sc1)C(=O)N[C@H](C[C@H]2CCNC2=O)[C@H](c3cyclopropyl)C(=O)N[C@H](C(=O)N4C[C@H](C[C@H]4c5cncs5)C(C)(C)C)C(C)C', formula: 'C38H46F2N6O9S2' },
    { name: 'Pibrentasvir', smiles: 'CC(C)c1nc(sc1)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@H]([C@@H](C)C)Oc4ccc(cc4)C(=O)N(C)C', formula: 'C50H67N7O5S2' },
    { name: 'Velpatasvir', smiles: 'CC(C)c1nc(sc1)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@H]([C@@H](C)C)Oc4ccc(cc4)C(=O)N(C)C', formula: 'C49H54N8O8' },
    { name: 'Voxilaprevir', smiles: 'CC(C)c1nc(sc1)C(=O)N[C@H](C[C@H]2CCNC2=O)[C@H](c3cyclopropyl)C(=O)N[C@H](C(=O)N4C[C@H](C[C@H]4c5cncs5)C(C)(C)C)C(C)C', formula: 'C48H61N7O8S2' },
    { name: 'Paclitaxel', smiles: 'CC1=C(C(=O)C2(C(C(C3(C(C2(C)C)C(C4C(C3O)C(C(C4(C)C)O)OC(=O)C)OC(=O)c5ccccc5)O)OC(=O)c6ccccc6)O)C(=O)O1)O', formula: 'C47H51NO14' },
    { name: 'Docetaxel', smiles: 'CC(C)(C)OC(=O)N[C@H](C(=O)O[C@@H]1C(C2(C(C(C(C3(C(C2(C)C)C(C4C(C3O)C(C(C4(C)C)O)OC(=O)C)OC(=O)c5ccccc5)O)O)C(=O)O1)C)O)c6ccccc6', formula: 'C43H53NO14' },
    { name: 'Vincristine', smiles: 'C[C@@H]1[C@H]2C[C@@](C(C(C(N)C2)OC(=O)C)(c3ccccc3)C(=O)OC)(c4c(c5ccccc5n4)C[C@H]1OC)C(O)=O', formula: 'C46H56N4O10' },
    { name: 'Vinblastine', smiles: 'C[C@@H]1[C@H]2C[C@@](C(C(C(N)C2)OC(=O)C)(c3ccccc3)C(=O)OC)(c4c(c5ccccc5n4)C[C@H]1OC)C(O)=O', formula: 'C46H58N4O9' },
    { name: 'Doxorubicin', smiles: 'C[C@H]1[C@H]([C@H](C(O[C@H]1O[C@H]2C[C@@](CC3=C(C4=C(C(=C23)O)C(=O)C5=C(C4=O)C=CC=C5O)O)(C(=O)CO)O)O)N)O', formula: 'C27H29NO11' },
    { name: 'Etoposide', smiles: 'C[C@@H]1[C@H]([C@@H]([C@H](O[C@H]1O[C@H]2[C@@H]3[C@H]4[C@H]([C@@H]2OC5=CC(=CC(=C5O)OC)OC)COC4=O)O)O)O', formula: 'C29H32O13' },
    { name: 'Cyclophosphamide', smiles: 'C1CN(P(=O)(OC1)N(CCCl)CCCl)CCCl', formula: 'C7H15Cl2N2O2P' },
    { name: 'Ifosfamide', smiles: 'C1CN(P(=O)(OC1)N(CCCl)CCCl)CCCl', formula: 'C7H15Cl2N2O2P' },
    { name: 'Cisplatin', smiles: '[NH3+][Pt-2]([NH3+])(Cl)Cl', formula: 'Cl2H6N2Pt' },
    { name: 'Carboplatin', smiles: 'C1CC(C1)(C(=O)O)C(=O)O.[NH3+][Pt-2]([NH3+])(O)O', formula: 'C6H12N2O4Pt' },
    { name: 'Oxaliplatin', smiles: 'C1CC(C(C1)N)N.[O-]C(=O)C(=O)[O-].[Pt+2]', formula: 'C8H14N2O4Pt' },
    { name: 'Bleomycin', smiles: 'C[C@H](N)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)N[C@H](C)C(=O)NCCS(=O)(=O)c1ccc(cc1)S(=O)(=O)NC2=NC(=CS2)c3ccc(cc3)S(=O)(=O)NC(=O)C(C)N', formula: 'C55H84N17O21S3' },
    { name: 'Methotrexate', smiles: 'CN(CC1=CN=C2N=C(N=C(N2)N)N1)C(=O)[C@H](CCC(=O)O)NC(=O)c3ccc(cc3)N', formula: 'C20H22N8O5' },
    { name: '5-Fluorouracil', smiles: 'Fc1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)O)O', formula: 'C9H11FN2O6' },
    { name: 'Gemcitabine', smiles: 'c1cn(c(=O)n(c1)N)C2C(C(C(O2)CO)F)F', formula: 'C9H11F2N3O4' },
    { name: 'Capecitabine', smiles: 'CCCCC(=O)OCOC1=C(C=C(C=C1)F)C(=O)NC(=O)N', formula: 'C15H22FN3O6' },
    { name: 'Tamoxifen', smiles: 'CCOc1ccc(cc1)/C(=C(\\c2ccccc2)/c3ccc(cc3)OCCN(C)C)/c4ccccc4', formula: 'C26H29NO' },
    { name: 'Anastrozole', smiles: 'CC(C)(c1ccc(cn1)CN)c2ccc(cn2)C#N', formula: 'C17H19N5' },
    { name: 'Letrozole', smiles: 'c1ccc(cc1)C(c2ccc(cn2)C#N)(c3ncncn3)c4ncncn4', formula: 'C17H11N5' },
    { name: 'Exemestane', smiles: 'C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=C)CCC4=CC(=O)C=C[C@]34C', formula: 'C20H24O2' },
    { name: 'Leuprolide', smiles: 'CC[C@H](C)C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N1)CC(C)C)CC(C)C)CC(C)C)CC(C)C)CC(C)C)CC(C)C)CC(C)C)CC(C)C)CC(C)C', formula: 'C59H84N16O12' },
    { name: 'Goserelin', smiles: 'CC(C)C[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N1)CCCNC(=N)N)CC2=CNC=N2)CC3=CC=C(O)C=C3)CC(=O)N)CC(=O)O)CO)CC4=CNC5=CC=CC=C54)C(=O)N[C@H](C(=O)O)CC(C)C)NC(=O)C1CCCC1', formula: 'C60H86N18O14' },
    { name: 'Triptorelin', smiles: 'CC(C)C[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N1)CCCNC(=N)N)CC2=CNC=N2)CC3=CC=C(O)C=C3)CC(=O)N)CC(=O)O)CO)CC4=CNC5=CC=CC=C54)C(=O)N[C@H](C(=O)O)CC(C)C)NC(=O)C1CCCC1', formula: 'C64H82N18O13' },
    { name: 'Bicalutamide', smiles: 'CC(C)(C(=O)NC1=CC(=C(C=C1)S(=O)(=O)C(F)(F)F)C#N)O', formula: 'C18H14F3N3O4S' },
    { name: 'Flutamide', smiles: 'CC(C)NC(=O)c1ccc(c(c1)C(F)(F)F)[N+](=O)[O-]', formula: 'C11H11F3N2O3' },
    { name: 'Nilutamide', smiles: 'CC(C)(C(=O)N1C(=O)N(C(=O)C1)c2ccc(cc2)[N+](=O)[O-])[N+](=O)[O-]', formula: 'C12H10F3N3O4' },
    { name: 'Enzalutamide', smiles: 'CN(C)c1ccc(cc1)C(=O)N2[C@H](C(=O)N(C2=S)c3cc(c(cc3F)C(F)(F)F)C#N)C', formula: 'C21H16F4N4OS' },
    { name: 'Abiraterone', smiles: 'C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=C(c4cnccc4)C)CCC4=CC(=O)C=C[C@]34C', formula: 'C24H31NO' },
    { name: 'Bevacizumab', smiles: 'heavy chain', formula: 'C6638H10160N1720O2104S44' },
    { name: 'Cetuximab', smiles: 'heavy chain', formula: 'C6486H10012N1724O2022S42' },
    { name: 'Trastuzumab', smiles: 'heavy chain', formula: 'C6470H10012N1728O2018S42' },
    { name: 'Rituximab', smiles: 'heavy chain', formula: 'C6416H9874N1688O1986S44' },
    { name: 'Adalimumab', smiles: 'heavy chain', formula: 'C6428H9912N1696O1994S46' },
    { name: 'Infliximab', smiles: 'heavy chain', formula: 'C6428H9912N1696O1994S46' },
    { name: 'Etanercept', smiles: 'fusion protein', formula: 'C2224H3478N590O684S30' },
    { name: 'Pembrolizumab', smiles: 'heavy chain', formula: 'C6358H9804N1692O1994S42' },
    { name: 'Nivolumab', smiles: 'heavy chain', formula: 'C6360H9790N1712O1988S42' },
    { name: 'Ipilimumab', smiles: 'heavy chain', formula: 'C6298H9724N1668O1998S40' },
    { name: 'Atezolizumab', smiles: 'heavy chain', formula: 'C6442H9938N1710O2020S44' },
    { name: 'Avelumab', smiles: 'heavy chain', formula: 'C6400H9880N1692O2014S40' },
    { name: 'Durvalumab', smiles: 'heavy chain', formula: 'C6430H9932N1720O2014S44' },
    { name: 'Osimertinib', smiles: 'CN(C)C/C=C/C(=O)Nc1cc(c(nc1N)c2cnc(n2)C)Nc3ccc(c(c3)OC)OC', formula: 'C28H33N7O2' },
    { name: 'Erlotinib', smiles: 'c1cc(c(cc1OCCOC)OCCOC)C#Cc2cnc(nc2Nc3cc(c(cc3)C#N)C#N)C#N', formula: 'C22H23N3O4' },
    { name: 'Gefitinib', smiles: 'c1c(c(cc(c1)Cl)F)Nc2c(c(nc(n2)C)OC)OC', formula: 'C22H24ClFN4O3' },
    { name: 'Lapatinib', smiles: 'c1ccc(cc1)Oc2ccc(cc2Nc3ncc(c(n3)CS(=O)(=O)C)c4ccc(o4)c5cnccn5)F', formula: 'C29H26ClFN4O4S' },
    { name: 'Sunitinib', smiles: 'CCN(CC)CCNC(=O)c1c(c(n[nH]1)C=C2C(=O)Nc3c2cccc3F)C', formula: 'C22H27FN4O2' },
    { name: 'Sorafenib', smiles: 'CNC(=O)c1cc(ccc1OC)Oc2ccc(cc2)NC(=O)Nc3ccc(c(c3)Cl)C(F)(F)F', formula: 'C21H16ClF3N4O3' },
    { name: 'Pazopanib', smiles: 'Cc1c(c(nc(n1)C)c2ccc(cc2)S(=O)(=O)N(C)C)Nc3ccc(cc3)N4CCN(CC4)C', formula: 'C21H23N7O2S' },
    { name: 'Axitinib', smiles: 'CNC(=O)c1ccccc1Sc2ccc(cc2)Nc3c(c(n[nH]3)C=Cc4ccccn4)C', formula: 'C22H18N4OS' },
    { name: 'Crizotinib', smiles: 'c1(c(c(ccc1Cl)F)Cl)C(c2c(c(ncn2)N)C(=O)N)OC', formula: 'C21H22Cl2FN5O' },
    { name: 'Ceritinib', smiles: 'c1c(nc(nc1C(F)(F)F)c2c(c(cn2)S(=O)(=O)N)C)N3CCN(CC3)C(=O)C(C)C', formula: 'C28H36F3N5O3S' },
    { name: 'Alectinib', smiles: 'c1cn(c(c1)C(c2ccccc2)(c3ccccc3)c4ccccc4)N5CCN(CC5)C(=O)C(C)(C)C', formula: 'C30H34N4O2' },
    { name: 'Brigatinib', smiles: 'c1(c(c(cn(c1)C)P(=O)(OC)OC)Cl)N2CCN(CC2)C(=O)C(c3cc(c(cc3)OC)OC)OC', formula: 'C29H39ClN5O5P' },
    { name: 'Lorlatinib', smiles: 'c1(c(c(cn(c1)C)C#N)C(=O)N)C(=O)N2CCC(CC2)(F)C(c3ccccc3)c4ccccc4)C', formula: 'C21H19FN4O2' },
    { name: 'Entrectinib', smiles: 'c1c(c(n(c(c1)C(=O)N)C)C)c2c(c(cn2)C(=O)N3C[C@H]4CC[C@H]3C4)c5ccccc5', formula: 'C31H34N4O2' },
    { name: 'Larotrectinib', smiles: 'c1c(c(n(c(c1)C(=O)N)C)C)c2c(c(cn2)C(=O)N3C[C@H]4CC[C@H]3C4)c5ccccc5', formula: 'C31H34N4O2' },
    { name: 'Ibrutinib', smiles: 'c1c(c(n(c(c1)C(=O)N)C)C(=O)c2cn(c3c2cccc3)C)c4cc(c(cc4)OC)OC', formula: 'C25H24N6O2' },
    { name: 'Acalabrutinib', smiles: 'c1c(c(n(c(c1)C(=O)N)C)C(=O)c2cn(c3c2cccc3)C)c4cc(c(cc4)OC)OC', formula: 'C26H23N7O2' },
    { name: 'Zanubrutinib', smiles: 'c1c(c(n(c(c1)C(=O)N)C(=O)c2cc(c(cc2)F)c3cn(c4c3cccc4)C)C)C', formula: 'C27H29N5O3' },
    { name: 'Venetoclax', smiles: 'c1c(c(c(c(c1)Cl)S(=O)(=O)N2C[C@H]3CC[C@H]2C3)Cl)c4c(c(cn4)c5ccc(c(c5)OC)OC)c6ccc(cn6)C(=O)NC(C)(C)C', formula: 'C45H50Cl2N7O7S' },
    { name: 'Idelalisib', smiles: 'c1c(c(n(c(c1)C(F)(F)F)C(=O)N)C)c2c(c(nc(n2)N)N)c3ccc(cc3)C(C)C', formula: 'C22H18F3N7O' },
    { name: 'Duvelisib', smiles: 'c1c(nc(nc1C(=O)N)N)Nc2c(c(n[nH]2)S(=O)(=O)c3cc(c(cc3)Cl)Cl)c4ccccc4', formula: 'C22H17Cl2N7O2S' },
    { name: 'Copanlisib', smiles: 'c1c(nc(n(c1)c2c(c(cn2)N)N)C)C(=O)N3CC(C(C3)O)(O)c4cc(c(cn4)N)OC', formula: 'C23H28N8O4' },
    { name: 'Alpelisib', smiles: 'c1c(nc(n(c1)C(=O)N)c2c(c(ncn2)N)S(=O)(=O)N)C(F)(F)F)C(C)C', formula: 'C19H22F3N5O2S' },
    { name: 'Taselisib', smiles: 'c1c(nc(nc1C(=O)NC(C)(C)C)c2c(c(cn2)C(=O)N(C)C)C(F)(F)F)Cl', formula: 'C21H23ClF3N7O2' },
    { name: 'Ruxolitinib', smiles: 'c1c(c(n(c(c1)C#N)C(c2nccn2)c3cccc(c3)C#N)C)C', formula: 'C17H18N6' },
    { name: 'Tofacitinib', smiles: 'c1(c(n(c(n1)C)C)C(=O)N[C@H]2CC[C@@H](C2)N(C)C(=O)C)C#N', formula: 'C16H20N6O' },
    { name: 'Baricitinib', smiles: 'c1c(c(n(c(c1)S(=O)(=O)N)C)C)C(c2cc(c(cn2)C(=O)N(C)C)C)C#N', formula: 'C16H17N7O2S' },
    { name: 'Upadacitinib', smiles: 'c1c(c(n(c(c1)S(=O)(=O)N)C(=O)NC(C)C)C)C(c2cc(c(cn2)C(=O)N(C)C)C)C#N', formula: 'C17H19N6O4S' },
    { name: 'Filgotinib', smiles: 'c1c(nc(nc1)c2c(c(cn2)C(=O)N)C(=O)N3CCC(CC3)c4ccc(cc4)OC(F)F)c5ccccc5', formula: 'C21H20N6O3' },
    { name: 'Ribociclib', smiles: 'CN1CCN(CC1)c2nc(c(nc2c3cc(c(cn3)C)C)N(C)C(=O)c4ccc(cc4)C)N(C)C', formula: 'C23H30N8O' },
    { name: 'Palbociclib', smiles: 'c1c(nc(c(c1)C(=O)N2CCN(CC2)C)C)c3c(c(cn3)C(=O)C)c4ccc(cc4)N', formula: 'C24H29N7O2' },
    { name: 'Abemaciclib', smiles: 'c1c(nc(c(c1)c2c(c(cn2)C)c3cnc(n3)N(CCF)C(C)C)F)c4cc(cn4)C(F)(F)F', formula: 'C27H32F3N7' },
    { name: 'Niraparib', smiles: 'c1ccc(cc1)C(=O)N[C@H]2CC[C@H](C2)c3cnc4cc(c(cc4n3)C)C', formula: 'C19H20N4O' },
    { name: 'Olaparib', smiles: 'c1c(cc(c(c1)F)C(=O)N2CCN(CC2)C(=O)c3c(c(cn3)C)C)C', formula: 'C24H23FN4O3' },
    { name: 'Rucaparib', smiles: 'c1cc2c(c(c1)F)c(c(=O)[nH]2)C(=O)N3CCN(CC3)CC4CCCC4', formula: 'C19H24FN3O2' },
    { name: 'Talazoparib', smiles: 'c1c(c(c(c(c1)F)C(=O)N2CCN(CC2)C(=O)c3c(c(cn3)C)C)F)C', formula: 'C19H16F2N4O3' },
    { name: 'Methane', smiles: 'C', formula: 'CH4' },
    { name: 'Propane', smiles: 'CCC', formula: 'C3H8' },
    { name: 'Butane', smiles: 'CCCC', formula: 'C4H10' },
    { name: 'Pentane', smiles: 'CCCCC', formula: 'C5H12' },
    { name: 'Hexane', smiles: 'CCCCCC', formula: 'C6H14' },
    { name: 'Heptane', smiles: 'CCCCCCC', formula: 'C7H16' },
    { name: 'Octane', smiles: 'CCCCCCCC', formula: 'C8H18' },
    { name: 'Nonane', smiles: 'CCCCCCCCC', formula: 'C9H20' },
    { name: 'Decane', smiles: 'CCCCCCCCCC', formula: 'C10H22' },
    { name: 'Toluene', smiles: 'Cc1ccccc1', formula: 'C7H8' },
    { name: 'o-Xylene', smiles: 'Cc1ccccc1C', formula: 'C8H10' },
    { name: 'Naphthalene', smiles: 'c1ccc2ccccc2c1', formula: 'C10H8' },
    { name: 'Anthracene', smiles: 'c1ccc2cc3ccccc3cc2c1', formula: 'C14H10' },
    { name: 'Phenanthrene', smiles: 'c1ccc2c(c1)ccc3ccccc23', formula: 'C14H10' },
    { name: 'Pyrene', smiles: 'c1cc2cc3ccc4cc(c1)c2c34', formula: 'C16H10' },
    { name: 'Aniline', smiles: 'Nc1ccccc1', formula: 'C6H7N' },
    { name: 'Phenol', smiles: 'Oc1ccccc1', formula: 'C6H6O' },
    { name: 'Benzoic Acid', smiles: 'O=C(O)c1ccccc1', formula: 'C7H6O2' },
    { name: 'Salicylic Acid', smiles: 'O=C(O)c1ccccc1O', formula: 'C7H6O3' },
    { name: 'Acetanilide', smiles: 'CC(=O)Nc1ccccc1', formula: 'C8H9NO' },
    { name: 'Cyclohexane', smiles: 'C1CCCCC1', formula: 'C6H12' },
    { name: 'Cyclopentane', smiles: 'C1CCCC1', formula: 'C5H10' },
    { name: 'Methylcyclohexane', smiles: 'CC1CCCCC1', formula: 'C7H14' },
    { name: 'Pyridine', smiles: 'c1ccncc1', formula: 'C5H5N' },
    { name: 'Pyrimidine', smiles: 'c1cncnc1', formula: 'C4H4N2' },
    { name: 'Purine', smiles: 'c1ncc2ncn[c:2]1', formula: 'C5H4N4' },
    { name: 'Indole', smiles: 'c1ccc2c(c1)c[nH]2', formula: 'C8H7N' },
    { name: 'Quinoline', smiles: 'c1ccc2c(c1)cccn2', formula: 'C9H7N' },
    { name: 'Isoquinoline', smiles: 'c1ccc2c(c1)cncc2', formula: 'C9H7N' },
    { name: 'Furan', smiles: 'c1ccoc1', formula: 'C4H4O' },
    { name: 'Thiophene', smiles: 'c1ccsc1', formula: 'C4H4S' },
    { name: 'Pyrrole', smiles: 'c1cc[nH]c1', formula: 'C4H5N' },
    { name: 'Imidazole', smiles: 'c1c[nH]cn1', formula: 'C3H4N2' },
    { name: 'Pyrazole', smiles: 'c1cc[nH]n1', formula: 'C3H4N2' },
    { name: 'Oxazole', smiles: 'c1cnco1', formula: 'C3H3NO' },
    { name: 'Isothiazole', smiles: 'c1cnsc1', formula: 'C3H3NS' },
    { name: 'Thiazole', smiles: 'c1cscn1', formula: 'C3H3NS' },
    { name: 'Piperidine', smiles: 'C1CCNCC1', formula: 'C5H11N' },
    { name: 'Morpholine', smiles: 'C1COCCN1', formula: 'C4H9NO' },
    { name: 'Thiomorpholine', smiles: 'C1CSCCN1', formula: 'C4H9NS' },
    { name: 'Piperazine', smiles: 'C1CNCCN1', formula: 'C4H10N2' },
    { name: 'Vinyl Chloride', smiles: 'C=CCl', formula: 'C2H3Cl' },
    { name: 'Chloroform', smiles: 'C(Cl)(Cl)Cl', formula: 'CHCl3' },
    { name: 'Carbon Tetrachloride', smiles: 'C(Cl)(Cl)(Cl)Cl', formula: 'CCl4' },
    { name: 'Dichloromethane', smiles: 'C(Cl)Cl', formula: 'CH2Cl2' },
    { name: 'Ethylene Glycol', smiles: 'OCCO', formula: 'C2H6O2' },
    { name: 'Diethylene Glycol', smiles: 'OCCOCCO', formula: 'C4H10O3' },
    { name: 'Acetic Acid', smiles: 'CC(=O)O', formula: 'C2H4O2' },
    { name: 'Formic Acid', smiles: 'C(=O)O', formula: 'CH2O2' },
    { name: 'Propionic Acid', smiles: 'CCC(=O)O', formula: 'C3H6O2' },
    { name: 'Butyric Acid', smiles: 'CCCC(=O)O', formula: 'C4H8O2' },
    { name: 'Valeric Acid', smiles: 'CCCCC(=O)O', formula: 'C5H10O2' },
    { name: 'Caproic Acid', smiles: 'CCCCCC(=O)O', formula: 'C6H12O2' },
    { name: 'Lactic Acid', smiles: 'CC(O)C(=O)O', formula: 'C3H6O3' },
    { name: 'Oxalic Acid', smiles: 'O=C(O)C(=O)O', formula: 'C2H2O4' },
    { name: 'Malonic Acid', smiles: 'O=C(O)CC(=O)O', formula: 'C3H4O4' },
    { name: 'Succinic Acid', smiles: 'O=C(O)CCC(=O)O', formula: 'C4H6O4' },
    { name: 'Glutaric Acid', smiles: 'O=C(O)CCCC(=O)O', formula: 'C5H8O4' },
    { name: 'Adipic Acid', smiles: 'O=C(O)CCCCC(=O)O', formula: 'C6H10O4' },
    { name: 'Maleic Acid', smiles: 'O=C(O)/C=C/C(=O)O', formula: 'C4H4O4' },
    { name: 'Fumaric Acid', smiles: 'O=C(O)/C=C\\C(=O)O', formula: 'C4H4O4' },
    { name: 'Citric Acid', smiles: 'O=C(O)CC(O)(CC(=O)O)C(=O)O', formula: 'C6H8O7' },
    { name: 'Tartaric Acid', smiles: 'O=C(O)C(O)C(O)C(=O)O', formula: 'C4H6O6' },
    { name: 'Ascorbic Acid', smiles: 'O=C1OC(C(O)CO)C(=C1O)O', formula: 'C6H8O6' },
    { name: 'Nicotine', smiles: 'CN1CCCC1c2cccnc2', formula: 'C10H14N2' },
    { name: 'Cocaine', smiles: 'CN1[C@H]2CC[C@@H]1[C@H]([C@H](C2)OC(=O)c3ccccc3)C(=O)OC', formula: 'C17H21NO4' },
    { name: 'Morphine', smiles: 'CN1CC[C@]23c4c5ccc(O)c4O[C@H]2[C@@H](O)C=C[C@H]3[C@H]1C5', formula: 'C17H19NO3' },
    { name: 'Heroin', smiles: 'CC(=O)OC1C=C[C@H]2[C@H]3Oc4c(ccc(OC(=O)C)c4)C[C@H]1[C@H]2N(C)CC3', formula: 'C21H23NO5' },
    { name: 'Amphetamine', smiles: 'CC(N)Cc1ccccc1', formula: 'C9H13N' },
    { name: 'Methamphetamine', smiles: 'CC(N(C)C)Cc1ccccc1', formula: 'C10H15N' },
    { name: 'MDMA', smiles: 'CC(NCC1=CC=C(OCO2)C2=C1)Cc3ccccc3', formula: 'C11H15NO2' },
    { name: 'LSD', smiles: 'CCN(CC)C(=O)[C@H]1CN(C)[C@@H]2Cc3c[nH]c4cccc(C2=C1)c34', formula: 'C20H25N3O' },
    { name: 'THC', smiles: 'CCCCCc1cc(O)c2c(c1)[C@@](C)(O)C[C@H]3[C@H]2OC(C)(C)[C@@H]3C=C', formula: 'C21H30O2' },
    { name: 'CBD', smiles: 'CCCCCc1cc(O)c(c(c1)C(C)(C)O)[C@H]2C=C(CC[C@H]2C)C', formula: 'C21H30O2' },
    { name: 'Psilocybin', smiles: 'C[N+](C)(C)CCC1=CNC2=C1C=C(OP(=O)([O-])[O-])C=C2', formula: 'C12H17N2O4P' },
    { name: 'DMT', smiles: 'CN(C)CCc1c[nH]c2ccccc12', formula: 'C12H16N2' },
    { name: 'Ketamine', smiles: 'CC1(C(=O)C2=C(C=C(Cl)C=C2)N1)C', formula: 'C13H16ClNO' },
    { name: 'Fentanyl', smiles: 'CCC(=O)N(c1ccccc1)C2CCN(CC2)CCc3ccccc3', formula: 'C22H28N2O' },
    { name: 'Remdesivir', smiles: 'C[C@H]([C@H]([C@H]([C@@](O1)(C#N)c2c(F)cc(I)cn2)O1)O)O[P@@](=O)(Nc3ccccc3)O[C@@H](C)C(=O)N(C)C', formula: 'C27H35N6O8P' },
    { name: 'Chloroquine', smiles: 'CCN(CC)CCCC(C)Nc1c2cc(Cl)ccc2nc1', formula: 'C18H26ClN3' },
    { name: 'Hydroxychloroquine', smiles: 'CCN(CCO)CCCC(C)Nc1c2cc(Cl)ccc2nc1', formula: 'C18H26ClN3O' },
    { name: 'Azithromycin', smiles: 'C[C@H]1O[C@H](C[C@@H](C)[C@@H](O)[C@H](C)O[C@@H]2O[C@H](C)[C@@H](O)[C@H](N(C)C)[C@@H]2O)[C@H](C)[C@@H](O[C@@H]3O[C@H](C)[C@H](O)[C@@H]3O)[C@]1(O)C(=O)O[C@H](C)[C@H](C)C[C@H](C)[C@H](C)[C@@H](C)[C@H](C)O[C@H](C)[C@H](C)C[C@@H]1CC(=O)N[C@@H](C)C(=O)O[C@H](C)C(=O)C', formula: 'C38H72N2O12' },
    { name: 'Dexamethasone', smiles: 'C[C@H]1[C@H]2[C@@H]([C@H]([C@]3(C(=C[C@H]12)C(=O)CO)C)F)C[C@H]4[C@@]3(C)C[C@H](C(=O)C(O)=C4)O', formula: 'C22H29FO5' },
    { name: 'Prednisone', smiles: 'C[C@H]1[C@H]2[C@@H](C[C@H]3[C@@]1(C(=O)C=C2)C[C@H](C3=O)[C@H]4C(=O)CO)O', formula: 'C21H26O5' },
    { name: 'Colchicine', smiles: 'COc1cc(OC)c(c(OC)c1)C(=O)N[C@H]2C3=CC=CC=C3[C@H](OC)C(=O)C2', formula: 'C22H25NO6' },
    { name: 'Allopurinol', smiles: 'c1cn([nH]c1=O)c2cn[nH]c2=O', formula: 'C5H4N4O' },
    { name: 'Febuxostat', smiles: 'CC(C)c1cc(c(cn1)C(=O)O)c2sc(n2)c3ccccc3', formula: 'C16H16N2O3S' },
    { 'name': 'Tadalafil', 'smiles': 'O=C1N(C)[C@@H]2[C@H](N1C(=O)c3c(C)cccc3C)Cc4c([C@H]2c5cccc(c5)C)n[nH]c4', 'formula': 'C22H19N3O4' },
    { 'name': 'Sildenafil', 'smiles': 'CCCC1=NN(C)C2=C1NC(=O)C(C)=N2', 'formula': 'C22H30N6O4S' },
    { 'name': 'Vardenafil', 'smiles': 'CCCC1=NN(C)C2=C1NC(=O)C(C)=N2', 'formula': 'C23H32N6O4S' },
    { 'name': 'Finasteride', 'smiles': 'C[C@]12CC[C@H]3[C@H]([C@@H]1C[C@H](C(=O)N[C@H](C(N)=O)C(C)(C)C)C2)CCC4=CC(=O)C[C@H]34', 'formula': 'C23H36N2O2' },
    { 'name': 'Dutasteride', 'smiles': 'C[C@]12CC[C@H]3[C@H]([C@@H]1C[C@H](C(=O)N[C@H](C(N)=O)C(C)(C)C)C2)CCC4=CC(=O)C[C@H]34', 'formula': 'C27H40N2O2' },
    { 'name': 'Tamsulosin', 'smiles': 'COc1ccc(c(c1)OC)CCNC(=O)C(c2ccccc2)c3ccccc3.Cl', 'formula': 'C20H28N2O5S' },
    { 'name': 'Terazosin', 'smiles': 'C1COC(O1)c2nc(c3c(n2)c(c(c(c3)OC)OC)N)N4CCN(CC4)C(=O)c5ccccc5', 'formula': 'C19H25N5O4' },
    { 'name': 'Doxazosin', 'smiles': 'C1COC(O1)c2nc(c3c(n2)c(c(c(c3)OC)OC)N)N4CCN(CC4)C(=O)c5ccccc5', 'formula': 'C23H25N5O5' },
    { 'name': 'Alfuzosin', 'smiles': 'C1COC(O1)c2nc(c3c(n2)c(c(c(c3)OC)OC)N)N(C)CCCCN4CCN(CC4)C(=O)c5ccccc5', 'formula': 'C19H27N5O4' },
    { 'name': 'Clopidogrel', 'smiles': 'CS(=O)(=O)O[C@@H](C(=O)OC)c1cc(sc1)c2ccccc2.Cl', 'formula': 'C16H16ClNO4S2' },
    { 'name': 'Prasugrel', 'smiles': 'CC(=O)O[C@H](C(=O)OC)c1cc(sc1)c2ccc(F)cc2', 'formula': 'C20H20FNO3S' },
    { 'name': 'Ticagrelor', 'smiles': 'CC(C)c1nc(c(nc1N)SCCCC[C@H](O)C(=O)O)N2CCC(CC2)c3ccccc3', 'formula': 'C23H28N6O4S' },
    { 'name': 'Rivaroxaban', 'smiles': 'O=C1N(c2ccc(Cl)cc2)[C@H]3[C@H](N1C(=O)C(N)=O)COC3=O', 'formula': 'C19H18ClN3O5S' },
    { 'name': 'Apixaban', 'smiles': 'O=C1N(c2ccc(OC)cc2)c3c(c(nn3C)C(=O)N)c4ccc(cc4)N5CCN(C(=O)C)CC5', 'formula': 'C25H25N5O4' },
    { 'name': 'Edoxaban', 'smiles': 'O=C1N(C)C(=O)c2c(N1c3ccc(Cl)cc3)cc(c(c2)C)S(=O)(=O)N4CCN(CC4)C', 'formula': 'C24H30ClN7O4S' },
    { 'name': 'Dabigatran', 'smiles': 'CCOC(=O)N1C(C(=O)N(C)C)c2c(c(n2C)c3cc(ccc3)C(=N)N)C1=O', 'formula': 'C34H41N7O5' },
succeeded,
    { 'name': 'Vitamin A (Retinol)', 'smiles': 'CC1=C(C(C(C)(C)C1)C=CC=C(C)C=CC=C(C)CO)C', 'formula': 'C20H30O' },
    { 'name': 'Vitamin C (Ascorbic Acid)', 'smiles': 'C(C(C1C(=O)C(=C(O1)O)O)O)O', 'formula': 'C6H8O6' },
    { 'name': 'Vitamin D3 (Cholecalciferol)', 'smiles': 'CC(C)CCCC(C)C1CCC2C1(C)CCC3C2=CC=C4C3(C)CCC(C4)O', 'formula': 'C27H44O' },
    { 'name': 'Vitamin E (Alpha-tocopherol)', 'smiles': 'CC1CCC(C(C1)O)(C)CCC(C)CCC(C)CCC(C)C', 'formula': 'C29H50O2' },
    { 'name': 'Vitamin K1 (Phylloquinone)', 'smiles': 'CC1=C(C(=O)c2ccccc2C1=O)CC=C(C)CCC(C)CCC(C)CCC(C)C', 'formula': 'C31H46O2' },
    { 'name': 'Folic Acid', 'smiles': 'C1=CC(=CC=C1C(=O)NC(CCC(=O)O)C(=O)O)N(CC2=CN=C3C(=N2)N=C(N)N3)C', 'formula': 'C19H19N7O6' },
    { 'name': 'Biotin (Vitamin B7)', 'smiles': 'C1C(C(S1)CCCCC(=O)O)NC(=O)N1', 'formula': 'C10H16N2O3S' },
    { 'name': 'Niacin (Vitamin B3)', 'smiles': 'C1=CC(=CN=C1)C(=O)O', 'formula': 'C6H5NO2' },
    { 'name': 'Pantothenic Acid (Vitamin B5)', 'smiles': 'CC(C)(CO)C(C(=O)NCCC(=O)O)O', 'formula': 'C9H17NO5' },
    { 'name': 'Pyridoxine (Vitamin B6)', 'smiles': 'CC1=C(C(=C(N=C1)CO)O)CO', 'formula': 'C8H11NO3' },
    { 'name': 'Riboflavin (Vitamin B2)', 'smiles': 'CC1=CC2=C(C=C1C)N(C3=NC(=O)NC(=O)C3=N2)C[C@H]([C@H]([C@H](CO)O)O)O', 'formula': 'C17H20N4O6' },
    { 'name': 'Thiamine (Vitamin B1)', 'smiles': 'CC1=NC=C(C(=N1)N)CN2C=C(SC2)CCO.Cl', 'formula': 'C12H17ClN4OS' },
    { 'name': 'Cyanocobalamin (Vitamin B12)', 'smiles': '[Co+3]123456789(N1=C(C(C(=N2C(=C(C)[C@](C(C(=C3[N](C(=C(C)C(=N4[C]([C@](C(=C5[N]6([C]([C@](C(=C7N(C(=C8[C](C(C(=C9N)C)C)(C)CC(=O)N)C)(C)CC(=O)N)C)(C)CC(=O)N[C@@H](C)O)[C@@H]9C)(C)C)C)CC(=O)N)C)C)(C)C(=O)N)C)C)C)C)C)CC(=O)N)C)C)C)C)[C@@H](C)CC(=O)N', 'formula': 'C63H88CoN14O14P' },
    { 'name': 'Menthol', 'smiles': 'CC(C)[C@H]1CC[C@H](C)C[C@@H]1O', 'formula': 'C10H20O' },
    { 'name': 'Camphor', 'smiles': 'C[C@]1(C)C(=O)C[C@@H]2CC[C@@]1(C)C2', 'formula': 'C10H16O' },
    { 'name': 'Limonene', 'smiles': 'CC1=CC[C@@H](CC1)C(=C)C', 'formula': 'C10H16' },
    { 'name': 'Pinene', 'smiles': 'C[C@]12C[C@@H](C1)C(C)(C)[C@H]2C=C', 'formula': 'C10H16' },
    { 'name': 'Eucalyptol', 'smiles': 'CC1(C2CC(C(C2)O1)(C)C)C', 'formula': 'C10H18O' },
    { 'name': 'Capsaicin', 'smiles': 'CNC(=O)CCCC/C=C/C(C)C', 'formula': 'C18H27NO3' },
    { 'name': 'Curcumin', 'smiles': 'COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)c(OC)c2)ccc1O', 'formula': 'C21H20O6' },
    { 'name': 'Resveratrol', 'smiles': 'c1cc(ccc1/C=C/c2ccc(cc2)O)O', 'formula': 'C14H12O3' },
    { 'name': 'Quercetin', 'smiles': 'c1cc(c(cc1O)O)c2c(oc3c(c2=O)cc(cc3O)O)O', 'formula': 'C15H10O7' },
    { 'name': 'Genistein', 'smiles': 'c1cc(c(cc1O)O)c2c(oc3c(c2=O)cc(cc3O)O)O', 'formula': 'C15H10O5' },
    { 'name': 'Daidzein', 'smiles': 'c1cc(c(cc1O)O)c2c(oc3c(c2=O)cc(cc3O)O)O', 'formula': 'C15H10O4' },
    { 'name': 'Epicatechin', 'smiles': 'c1cc(c(cc1O)O)c2c(oc3c(c2O)cc(cc3O)O)O', 'formula': 'C15H14O6' },
    { 'name': 'Gallic Acid', 'smiles': 'c1cc(c(c(c1)O)O)C(=O)O', 'formula': 'C7H6O5' },
    { 'name': 'Vanillin', 'smiles': 'COc1cc(ccc1O)C=O', 'formula': 'C8H8O3' },
    { 'name': 'Cinnamaldehyde', 'smiles': 'c1ccccc1C=CC=O', 'formula': 'C9H8O' },
    { 'name': 'Eugenol', 'smiles': 'COc1cc(ccc1O)CC=C', 'formula': 'C10H12O2' },
    { 'name': 'Zingiberene', 'smiles': 'CC(C)c1ccc(c(c1)C)CC[C@H]2C=C(C)CC2', 'formula': 'C15H24' },
    { 'name': 'Progesterone', 'smiles': 'C[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C', 'formula': 'C21H30O2' },
    { 'name': 'Cortisol', 'smiles': 'C[C@]12C[C@H](C3[C@H]([C@@H]1C[C@H]4[C@H]2C(=O)C=C4)CCC3=O)O', 'formula': 'C21H30O5' },
    { 'name': 'Aldosterone', 'smiles': 'C[C@]12C[C@H](C3[C@H]([C@@H]1C[C@H]4[C@H]2C(=O)C=C4)CC(=O)C3=O)O', 'formula': 'C21H28O5' },
    { 'name': 'Prednisolone', 'smiles': 'C[C@H]1[C@H]2[C@@H](C[C@H]3[C@@]1(C(=O)C=C2)C[C@H](C3=O)[C@H]4C(=O)CO)O', 'formula': 'C21H28O5' },
    { 'name': 'Betamethasone', 'smiles': 'C[C@H]1[C@H]2[C@@H]([C@H]([C@]3(C(=C[C@H]12)C(=O)CO)C)F)C[C@H]4[C@@]3(C)C[C@H](C(=O)C(O)=C4)O', 'formula': 'C22H29FO5' },
    { 'name': 'Triamcinolone', 'smiles': 'C[C@]12C[C@H](C3[C@H]([C@@H]1C[C@H]4[C@H]2C(=O)C=C4F)CCC3=O)O', 'formula': 'C21H27FO6' },
    { 'name': 'Fluocinolone Acetonide', 'smiles': 'C[C@]12C[C@H](C3[C@H]([C@@H]1C[C@H]4[C@H]2C(=O)C=C4F)CCC3=O)OC(C)(C)O1', 'formula': 'C24H30F2O6' },
    { 'name': 'Fluticasone Propionate', 'smiles': 'C[C@H]1[C@H]2[C@@H](C[C@H]3[C@]1(C(=O)C=C2)C[C@H](C3=O)[C@H]4C(=O)SCC(=O)C)F', 'formula': 'C25H31F3O5S' },
    { 'name': 'Budesonide', 'smiles': 'C[C@H]1C[C@H]2[C@H]3[C@H](C=C(C2)C(=O)C[C@H]1O)OC(O3)CCC', 'formula': 'C25H34O6' },
    { 'name': 'Mometasone Furoate', 'smiles': 'C[C@H]1C[C@H]2[C@H]3[C@H](C=C(C2Cl)C(=O)C[C@H]1OC(=O)c4occc4)C3(C)Cl', 'formula': 'C27H30Cl2O6' },
    { 'name': 'Spironolactone', 'smiles': 'C[C@]12CC[C@@H]3[C@H]([C@@H]1C[C@H](C(=O)S[C@H]2SC(=O)C)C)CCC4=CC(=O)CC[C@H]34', 'formula': 'C24H32O4S' },
    { 'name': 'Eplerenone', 'smiles': 'C[C@]12CC[C@@H]3[C@H]([C@@H]1C[C@H](C(=O)O[C@H]2OC(=O)C)C)CCC4=CC(=O)CC[C@H]34', 'formula': 'C24H30O6' },
    { 'name': 'Amiodarone', 'smiles': 'CCCC(=O)c1c(c(cc2c1OC(=O)C=C2)I)c3ccc(cc3)N(CC)CC', 'formula': 'C25H29I2NO3' },
    { 'name': 'Dronedarone', 'smiles': 'CCCC(=O)c1c(c(cc2c1OC(=O)C=C2)S(=O)(=O)N(C)C)c3ccc(cc3)N(CC)CC', 'formula': 'C31H44N2O5S' },
    { 'name': 'Sotalol', 'smiles': 'CS(=O)(=O)Nc1ccc(cc1)C(O)CN(C)C', 'formula': 'C12H20N2O3S' },
    { 'name': 'Propafenone', 'smiles': 'CCC(=O)Nc1ccccc1OCC(O)CN(C)C', 'formula': 'C21H27N2O3' },
    { 'name': 'Flecainide', 'smiles': 'FC(F)(F)COc1ccccc1C(=O)N(C)CCCCCCCCN2CCCCC2', 'formula': 'C17H20F6N2O3' },
    { 'name': 'Lidocaine', 'smiles': 'CCN(CC)C(=O)Cc1c(C)cc(C)cc1C', 'formula': 'C14H22N2O' },
    { 'name': 'Mexiletine', 'smiles': 'CC(C)OC(=O)c1c(C)cc(C)cc1C', 'formula': 'C11H17NO' },
    { 'name': 'Tocainide', 'smiles': 'CC(N)C(=O)Nc1c(C)cc(C)cc1C', 'formula': 'C11H16N2O' },
    { 'name': 'Propofol', 'smiles': 'CC(C)c1cc(C(C)C)c(c(c1)C(C)C)O', 'formula': 'C12H18O' },
    { 'name': 'Etomidate', 'smiles': 'CCOC(=O)c1cn(C[C@@H](C)c2ccccc2)c(n1)C', 'formula': 'C14H16N2O2' },
    { 'name': 'Midazolam', 'smiles': 'Clc1cc2c(cc1F)N=C(C(=O)N2c3ccccc3)c4cn[nH]c4', 'formula': 'C18H13ClFN4' },
    { 'name': 'Lorazepam', 'smiles': 'O=C1N(c2ccccc2)C(=O)C(c3cc(Cl)ccc3Cl)N1', 'formula': 'C15H10Cl2N2O2' },
    { 'name': 'Alprazolam', 'smiles': 'Cc1nnc2n1-c3ccc(c(c3)Cl)C(=N/c4ccccc4/C2=O)C', 'formula': 'C17H13ClN4' },
    { 'name': 'Clonazepam', 'smiles': 'O=[N+]([O-])c1ccc2c(c1)N=C(c3ccccc3Cl)C(=O)N2', 'formula': 'C15H10ClN3O3' },
    { 'name': 'Zolpidem', 'smiles': 'CC1=C(C(=C(N=C1)c2ccc(C)cc2)C(=O)N(C)C)c3ccc(C)cc3', 'formula': 'C19H21N3O' },
    { 'name': 'Zaleplon', 'smiles': 'c1ccc(cc1)c2c(c(cn2C#N)c3cnccn3)C', 'formula': 'C17H15N5' },
    { 'name': 'Eszopiclone', 'smiles': 'O=C1N2C(C(c3cc(Cl)ccn3)N(C2=O)c4ncccn4)=C(c5ccccc5)N1C', 'formula': 'C17H17ClN6O3' },
    { 'name': 'Buspirone', 'smiles': 'N1CCN(CC1)CCCCN2C(=O)C3=C(C2=O)C=CC=C3', 'formula': 'C21H31N5O2' },
    { 'name': 'Mirtazapine', 'smiles': 'CN1CCN(CC1)C2=NC3=C(C=CC=C3)N=C2C4=CC=CC=C4', 'formula': 'C17H19N3' },
    { 'name': 'Trazodone', 'smiles': 'N1CCN(CC1)CCCOc2ccc(c(c2)Cl)c3ncccn3', 'formula': 'C19H22ClN5O' },
    { 'name': 'Bupropion', 'smiles': 'CC(C)(C)NC(C)c1ccc(Cl)cc1', 'formula': 'C13H18ClNO' },
    { 'name': 'Atomoxetine', 'smiles': 'COc1ccccc1[C@H](C)Nc2ccccc2', 'formula': 'C17H21NO' },
    { 'name': 'Methylphenidate', 'smiles': 'C1CCC(C(C1)C(=O)OC)c2ccccn2', 'formula': 'C14H19NO2' },
    { 'name': 'Lisdexamfetamine', 'smiles': 'C[C@H](CC(=O)N)NC(=O)[C@H](C)Cc1ccccc1', 'formula': 'C15H25N3O' },
    { 'name': 'Memantine', 'smiles': 'CC1(C)CC2CC(C1)CC(C2)N', 'formula': 'C12H21N' },
    { 'name': 'Donepezil', 'smiles': 'COc1cc(OC)c2c(c1)C(=O)C(CC2=O)CN3CCN(CC3)c4ccccc4', 'formula': 'C24H29NO3' },
    { 'name': 'Rivastigmine', 'smiles': 'CCN(C)C(=O)Oc1ccc(cc1)[C@H](C)N(C)C', 'formula': 'C14H22N2O2' },
    { 'name': 'Galantamine', 'smiles': 'CN1C[C@H]2c3cc(OC)c(O)cc3[C@@H]4[C@H](CC[C@H]24)C1', 'formula': 'C17H21NO3' },
    { 'name': 'Levodopa', 'smiles': 'c1cc(c(cc1O)O)C[C@H](C(=O)O)N', 'formula': 'C9H11NO4' },
    { 'name': 'Carbidopa', 'smiles': 'c1cc(c(cc1O)O)C[C@](C(=O)O)(N)N', 'formula': 'C10H14N2O4' },
    { 'name': 'Entacapone', 'smiles': 'O=C(c1ccc(cc1)[N+](=O)[O-])/C=C(\\N=N/c2ccc(cc2)O)/C(=O)N(CC)CC', 'formula': 'C14H15N3O5' },
    { 'name': 'Tolcapone', 'smiles': 'O=C(c1ccc(cc1)[N+](=O)[O-])c2c(c(c(cc2O)C)O)C', 'formula': 'C14H11NO5' },
    { 'name': 'Selegiline', 'smiles': 'CN(CC#C)C(C)Cc1ccccc1', 'formula': 'C13H17N' },
    { 'name': 'Rasagiline', 'smiles': 'C#CCN(C)Cc1ccccc1', 'formula': 'C12H13N' },
    { 'name': 'Pramipexole', 'smiles': 'CC(C)N(C)S(=O)(=O)c1sc2c(c1)CCCC2', 'formula': 'C10H17N3S' },
    { 'name': 'Ropinirole', 'smiles': 'CCN(CC)CCCC1(Cc2ccccc2)c3cc(c(cc3N1)O)C', 'formula': 'C16H24N2O' },
    { 'name': 'Amantadine', 'smiles': 'C1C2CC3CC1CC(C2)(C3)N', 'formula': 'C10H17N' },
    { 'name': 'Sumatriptan', 'smiles': 'CN(C)S(=O)(=O)Cc1ccc2c(c1)c(c[nH]2)CN(C)C', 'formula': 'C14H21N3O2S' },
    { 'name': 'Rizatriptan', 'smiles': 'CN1CCN(CC1)CCc2c[nH]c3c2cc(cc3)C#N', 'formula': 'C15H19N5' },
    { 'name': 'Zolmitriptan', 'smiles': 'CN1CCN(CC1)CCc2c[nH]c3c2cc(cc3)C(=O)N(C)C', 'formula': 'C16H21N3O2' },
    { 'name': 'Naratriptan', 'smiles': 'CN(C)S(=O)(=O)c1ccc2c(c1)c(c[nH]2)CCCN(C)C', 'formula': 'C17H25N3O2S' },
    { 'name': 'Almotriptan', 'smiles': 'CN(C)S(=O)(=O)c1ccc2c(c1)c(c[nH]2)CCN3CCCCC3', 'formula': 'C17H25N3O2S' },
    { 'name': 'Eletriptan', 'smiles': 'c1ccc(cc1)S(=O)(=O)N2CC[C@@H](C2)c3c[nH]c4c3cccc4', 'formula': 'C22H26N2O2S' },
    { 'name': 'Frovatriptan', 'smiles': 'CN1[C@H]2CC[C@H]1c3c(c[nH]c3C(=O)N)C(N)=O', 'formula': 'C14H17N3O' },
    { 'name': 'Gabapentin Enacarbil', 'smiles': 'CC(C)OC(=O)O[C@H](C)CC1(CCCCC1)CC(=O)O', 'formula': 'C16H27NO4' },
    { 'name': 'Clobazam', 'smiles': 'O=C1N(C)c2cc(Cl)ccc2C(=O)N1c3ccccc3', 'formula': 'C16H13ClN2O2' },
    { 'name': 'Felbamate', 'smiles': 'C(C(COC(=O)N)COC(=O)N)c1ccccc1', 'formula': 'C11H14N2O4' },
    { 'name': 'Isotretinoin', 'smiles': 'CC1=C(C(=CC=C1C=CC=C(C)C(=O)O)C)C', 'formula': 'C20H28O2' },
    { 'name': 'Tretinoin', 'smiles': 'CC1=C(C(=CC=C1C=CC=C(C)C(=O)O)C)C', 'formula': 'C20H28O2' },
    { 'name': 'Adapalene', 'smiles': 'c1ccc(cc1)c2cc(c(c(c2)c3ccccc3)C(=O)O)OC', 'formula': 'C28H28O3' },
    { 'name': 'Tazarotene', 'smiles': 'CC(C)(C)c1cc(c(c(c1)C#N)S(=O)(=O)c2ncccn2)OC', 'formula': 'C21H21N3O3S' },
    { 'name': 'Calcipotriene', 'smiles': 'C[C@H](CCCC(C)(C)O)C1CCC2C1(C)CCC3C2=CC=C4C3(C)CCC(C4O)C(=C)C', 'formula': 'C27H40O3' },
    { 'name': 'Acitretin', 'smiles': 'COc1cc(C=CC=C(C)C=CC=C(C)C(=O)O)c(C)cc1C', 'formula': 'C21H26O3' },
    { 'name': 'Minoxidil', 'smiles': 'N1C(=NC(=C1N2CCCCC2)N)N(=O)O', 'formula': 'C9H15N5O' },
    { 'name': 'Anthralin', 'smiles': 'c1ccc2c(c1)C(=O)c3c(c(O)cc(c3)O)C2=O', 'formula': 'C14H10O3' },
    { 'name': 'Calcipotriol', 'smiles': 'C[C@H](CCCC(C)(C)O)C1CCC2C1(C)CCC3C2=CC=C4C3(C)CCC(C4O)C(=C)C', 'formula': 'C27H40O3' },
    { 'name': 'Betamethasone Dipropionate', 'smiles': 'CCC(=O)O[C@H]1[C@@H](C)C(=O)C2=C[C@@H]3[C@H](C(C)(C)F)C[C@@H](OC(=O)CC)[C@@]3(C)[C@@H]2[C@H]1OC(=O)CC', 'formula': 'C28H37FO7' },
    { 'name': 'Clobetasol Propionate', 'smiles': 'C[C@H]1[C@@H](OC(=O)CC)C[C@H]2[C@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(Cl)[C@H](O)[C@]21C', 'formula': 'C25H32ClFO5' },
    { 'name': 'Halobetasol Propionate', 'smiles': 'C[C@H]1[C@@H](OC(=O)CC)C[C@H]2[C@H]3C[C@H](F)C4=CC(=O)C=C[C@]4(C)[C@@]3(Cl)[C@H](O)[C@]21C', 'formula': 'C25H31ClF2O5' },
    { 'name': 'Diflorasone Diacetate', 'smiles': 'CC(=O)O[C@H]1[C@H](C)[C@@H](OC(=O)C)C2=C[C@H]3[C@H](C(C)(F)F)[C@@H](O)[C@@]3(C)[C@@H]2C1', 'formula': 'C26H32F2O7' },
    { 'name': 'Amcinonide', 'smiles': 'C[C@@]1(O)C[C@H]2[C@H]3[C@H]([C@@H]1OC(=O)C)[C@@]4(F)C[C@@H](OC(C)(C)O)C=C4C(=O)C3=CC2=O', 'formula': 'C28H35FO7' },
    { 'name': 'Desoximetasone', 'smiles': 'C[C@]12C[C@H](O)[C@H]3[C@H]([C@@H]1C(=O)CO)[C@@H](F)C=C4C3(C)CCC(=O)C4=C2', 'formula': 'C22H29FO4' },
    { 'name': 'Fluocinonide', 'smiles': 'C[C@]12C[C@H](OC(=O)C)[C@H]3[C@H]([C@@H]1C(=O)CO)[C@@H](F)C=C4[C@@]3(C)OC(C)(C)O[C@H]4C=C2', 'formula': 'C26H32F2O7' },
    { 'name': 'Hydrocortisone', 'smiles': 'C[C@]12C[C@H](O)[C@H]3[C@H]([C@@H]1CCC2=O)CCC4=CC(=O)C=C[C@]34C', 'formula': 'C21H30O5' },
    { 'name': 'Clotrimazole', 'smiles': 'c1ccccc1C(c2ccccc2)(c3ccccc3)n4ccnc4', 'formula': 'C22H17ClN2' },
    { 'name': 'Miconazole', 'smiles': 'c1cc(c(cc1Cl)Cl)c(c(n2)c(c3C)C(=O)N)CO2', 'formula': 'C18H14Cl4N2O' },
    { 'name': 'Ketoconazole', 'smiles': 'CC(=O)N1CCN(CC1)c2ccc(cc2)OC3CCN(CC3)C(=O)c4ccc(cn4)Cl', 'formula': 'C26H28Cl2N4O4' },
    { 'name': 'Itraconazole', 'smiles': 'CCC(C)N1N=C(C(=N1)c2ccc(cc2)Cl)c3ccc(cc3)N4CCN(CC4)c5ccccc5', 'formula': 'C35H38Cl2N8O4' },
    { 'name': 'Fluconazole', 'smiles': 'c1cc(c(cc1F)F)C(c2ncncn2)(c3ncncn3)O', 'formula': 'C13H12F2N6O' },
    { 'name': 'Voriconazole', 'smiles': 'C[C@H]([C@@H](c1cn(cn1)C)c2ccc(F)cc2)n3cncn3', 'formula': 'C16H14F3N5O' },
    { 'name': 'Posaconazole', 'smiles': 'CC[C@H]([C@H](c1cn(cn1)C)c2ccc(F)cc2)N3CCN(CC3)c4ccc(cc4)N5C(=O)N(C(=O)N5C)C(C)C', 'formula': 'C37H42F2N8O4' },
    { 'name': 'Isavuconazole', 'smiles': 'C[C@@H]([C@@H](c1cn(cn1)C)c2ccc(F)cc2)N3C(=O)C(=C(S3)c4ccc(F)cc4)c5ccccc5', 'formula': 'C22H17F2N5OS' },
    { 'name': 'Terbinafine', 'smiles': 'CC(C)(C)C#CC[C@H](C)N(C)Cc1ccccc1', 'formula': 'C21H25N' },
    { 'name': 'Naftifine', 'smiles': 'CN(Cc1ccccc1)C=Cc2c(cccc2)C', 'formula': 'C21H21N' },
    { 'name': 'Butenafine', 'smiles': 'CN(Cc1c(C)cc(C)cc1C)C=Cc2ccccc2', 'formula': 'C23H27N' },
    { 'name': 'Amorolfine', 'smiles': 'CC(C)(C)C1CC(C)(C)N(C1)Cc2ccc(cc2)C(C)(C)C', 'formula': 'C21H35NO' },
    { 'name': 'Ciclopirox', 'smiles': 'O=C1C=C(C)C(=C(N1O)c2ccccc2)C', 'formula': 'C12H17NO2' },
    { 'name': 'Griseofulvin', 'smiles': 'COc1c(Cl)c(c2c(c1)C(=O)[C@](C)(OC)[C@@H]3C2=C(OC)C(=O)C3)C', 'formula': 'C17H17ClO6' },
    { 'name': 'Nystatin', 'smiles': 'C[C@H]1O[C@H](C[C@@H](C)[C@@H](O)[C@H](C)O[C@@H]2O[C@H](C)[C@@H](O)[C@H](N)[C@@H]2O)[C@H](C)[C@@H](O[C@@H]3O[C@H](C)[C@H](O)[C@@H]3O)[C@]1(O)C(=O)O[C@H](C)[C@H](C)C[C@H](C)[C@H](C)[C@@H](C)[C@H](C)O[C@H](C)[C@H](C)C[C@@H]1CC(=O)N[C@@H](C)C(=O)O[C@H](C)C(=O)C', 'formula': 'C47H75NO17' },
    { 'name': 'Amphotericin B', 'smiles': 'C[C@H]1O[C@H](C[C@@H](C)[C@@H](O)[C@H](C)O[C@@H]2O[C@H](C)[C@@H](O)[C@H](N)[C@@H]2O)[C@H](C)[C@@H](O[C@@H]3O[C@H](C)[C@H](O)[C@@H]3O)[C@]1(O)C(=O)O[C@H](C)[C@H](C)C[C@H](C)[C@H](C)[C@@H](C)[C@H](C)O[C@H](C)[C@H](C)C[C@@H]1CC(=O)N[C@@H](C)C(=O)O[C@H](C)C(=O)C', 'formula': 'C47H73NO17' },
    { 'name': 'Mupirocin', 'smiles': 'CC[C@H](C)[C@H](O)C[C@H](O)C(C)C(=O)OCCCCCCC(=O)O', 'formula': 'C26H44O9' },
    { 'name': 'Retapamulin', 'smiles': 'CC1(C)C[C@@H]2C[C@@H]1C(=O)C=C(C)C(O[C@H]3C[C@H](S(=O)(=O)c4ccccc4)C[C@H](C)O3)C2', 'formula': 'C30H47NO5S' },
    { 'name': 'Metronidazole', 'smiles': 'O=[N+]([O-])c1nccn1CCO', 'formula': 'C6H9N3O3' },
    { 'name': 'Tinidazole', 'smiles': 'O=[N+]([O-])c1nccn1CCS(=O)(=O)CC', 'formula': 'C8H13N3O4S' },
    { 'name': 'Ivermectin', 'smiles': 'CCC(C)C1OC2C(C(C(C(O2)C=CC=C3C(C(C=C(C)C3)C)OC4C(C(C(C(O4)C)O)OC5C(C(C(C(O5)C)O)OC)O)O)OC)C)OC1', 'formula': 'C48H74O14' },
    { 'name': 'Permethrin', 'smiles': 'CC(C)=C(Cl)C(=O)OCc1cccc(c1)Oc2ccccc2', 'formula': 'C21H20Cl2O3' },
    { 'name': 'Lindane', 'smiles': 'C1(C(C(C(C(C1Cl)Cl)Cl)Cl)Cl)Cl)Cl', 'formula': 'C6H6Cl6' },
    { 'name': 'Malathion', 'smiles': 'CCOC(=S)SP(S)(OCC)Sc1ccccc1', 'formula': 'C10H19O6PS2' },
    { 'name': 'Chlorhexidine', 'smiles': 'Clc1ccc(cc1)NC(=N)NC(=N)NCCCCCCN(=N)NC(=N)Nc2ccc(Cl)cc2', 'formula': 'C22H30Cl2N10' },
    { 'name': 'Triclosan', 'smiles': 'c1cc(c(cc1Cl)O)c2c(c(cc(c2)Cl)Cl)Cl', 'formula': 'C12H7Cl3O2' },
    { 'name': 'Hexachlorophene', 'smiles': 'c1c(c(c(cc1O)C(c2c(c(c(cc2O)Cl)Cl)Cl)Cl)Cl)Cl)Cl', 'formula': 'C13H6Cl6O2' },
    { 'name': 'Povidone-iodine', 'smiles': '[I-].[I-].c1ccc(cc1)C(=O)N1CCCC1=O', 'formula': 'C6H9INO' }
];
