
export type Molecule = {
  name: string;
  smiles: string;
  formula: string;
};

export const molecules: Molecule[] = [
    { name: 'Aspirin', smiles: 'CC(=O)Oc1ccccc1C(=O)O', formula: 'C9H8O4' },
    { name: 'Ibuprofen', smiles: 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O', formula: 'C13H18O2' },
    { name: 'Paracetamol', smiles: 'CC(=O)NC1=CC=C(O)C=C1', formula: 'C8H9NO2' },
    { name: 'Caffeine', smiles: 'CN1C=NC2=C1C(=O)N(C(=O)N2C)C', formula: 'C8H10N4O2' },
    { name: 'Metformin', smiles: 'CN(C)C(=N)N=C(N)N', formula: 'C4H11N5' },
    { name: 'Amoxicillin', smiles: 'CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(O)C=C3)N)C(=O)O)C', formula: 'C16H19N3O5S' },
    { name: 'Diazepam (Valium)', smiles: 'CN1C2=C(C=C(C=C2)Cl)C(=NC1=O)C3=CC=CC=C3', formula: 'C16H13ClN2O' },
    { name: 'Sertraline (Zoloft)', smiles: 'CN[C@H]1CC[C@@H](C2=CC=CC=C12)C3=CC(=C(C=C3)Cl)Cl', formula: 'C17H17Cl2N' },
    { name: 'Lisinopril', smiles: 'C[C@H](N)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCCCN)C(=O)O', formula: 'C21H31N3O5' },
    { name: 'Atorvastatin (Lipitor)', smiles: 'CC(C)c1c(c(n(c1c2ccc(cc2)F)C(C)C)CC[C@H](C[C@H](CC(=O)O)O)O)c3ccccc3', formula: 'C33H35FN2O5' },
    { name: 'Imatinib (Gleevec)', smiles: 'Cc1ccc(cc1)c2cc(c(cn2)Nc3ncc(c(n3)C)-c4cccc(c4)C(F)(F)F)C(=O)N5CCN(CC5)C', formula: 'C29H31F3N7O' },
    { name: 'Penicillin G', smiles: 'CC1(C(N2C(S1)C(C2=O)NC(=O)Cc3ccccc3)C(=O)O)C', formula: 'C16H18N2O4S' },
    { name: 'Ciprofloxacin', smiles: 'C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O', formula: 'C17H18FN3O3' },
    { name: 'Warfarin', smiles: 'CC(=O)CC(C1=C(C=CC=C1)O)C2=C(C(=O)OC3=CC=CC=C23)O', formula: 'C19H16O4' },
    { name: 'Theophylline', smiles: 'CN1C=NC2=C1C(=O)NC(=O)N2C', formula: 'C7H8N4O2' },
    { name: 'Dopamine', smiles: 'C1=CC(=C(C=C1CCN)O)O', formula: 'C8H11NO2' },
    { name: 'Serotonin', smiles: 'C1=CC=C2C(=C1)C(=CN2)CCN', formula: 'C10H12N2O' },
    { name: 'Adrenaline (Epinephrine)', smiles: 'CNC[C@H](C1=CC(=C(C=C1)O)O)O', formula: 'C9H13NO3' },
    { name: 'Glucose', smiles: 'C(C1C(C(C(C(O1)O)O)O)O)O)O', formula: 'C6H12O6' },
    { name: 'Fructose', smiles: 'C(C1C(C(C(O1)(CO)O)O)O)O', formula: 'C6H12O6' },
    { name: 'Sucrose', smiles: 'C(C1C(C(C(C(O1)O)O)O)O)OC2(C(C(C(O2)CO)O)O)CO', formula: 'C12H22O11' },
    { name: 'Cholesterol', smiles: 'CC(C)CCCC(C)C1CCC2C1(CCC3C2CC=C4C3(CCC(C4)O)C)C', formula: 'C27H46O' },
    { name: 'Testosterone', smiles: 'C[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C', formula: 'C19H28O2' },
    { name: 'Estradiol', smiles: 'C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O', formula: 'C18H24O2' },
    { name: 'Benzene', smiles: 'c1ccccc1', formula: 'C6H6' },
    { name: 'Ethanol', smiles: 'CCO', formula: 'C2H6O' },
    { name: 'Methanol', smiles: 'CO', formula: 'CH4O'},
    { name: 'Glycerol', smiles: 'C(C(CO)O)O', formula: 'C3H8O3'},
    { name: 'Acetone', smiles: 'CC(=O)C', formula: 'C3H6O'},
    { name: 'Formaldehyde', smiles: 'C=O', formula: 'CH2O'},
    { name: 'Urea', smiles: 'C(=O)(N)N', formula: 'CH4N2O'},
    { name: 'Glycine', smiles: 'C(C(=O)O)N', formula: 'C2H5NO2' },
    { name: 'Alanine', smiles: 'C[C@H](C(=O)O)N', formula: 'C3H7NO2' },
    { name: 'Valine', smiles: 'CC(C)[C@H](C(=O)O)N', formula: 'C5H11NO2' },
    { name: 'Leucine', smiles: 'CC(C)C[C@H](C(=O)O)N', formula: 'C6H13NO2' },
    { name: 'Isoleucine', smiles: 'CC[C@H](C)[C@H](C(=O)O)N', formula: 'C6H13NO2' },
    { name: 'Proline', smiles: 'C1CC(NC1)C(=O)O', formula: 'C5H9NO2' },
    { name: 'Phenylalanine', smiles: 'c1ccc(cc1)C[C@H](C(=O)O)N', formula: 'C9H11NO2' },
    { name: 'Tryptophan', smiles: 'c1ccc2c(c1)c(c[nH]2)C[C@H](C(=O)O)N', formula: 'C11H12N2O2' },
    { name: 'Tyrosine', smiles: 'c1cc(ccc1C[C@H](C(=O)O)N)O', formula: 'C9H11NO3' },
    { name: 'Aspartic Acid', smiles: 'C([C@H](C(=O)O)N)C(=O)O', formula: 'C4H7NO4' },
    { name: 'Glutamic Acid', smiles: 'C(CC(=O)O)[C@H](C(=O)O)N', formula: 'C5H9NO4' },
    { name: 'Asparagine', smiles: 'C([C@H](C(=O)O)N)C(=O)N', formula: 'C4H8N2O3' },
    { name: 'Glutamine', smiles: 'C(CC(=O)N)[C@H](C(=O)O)N', formula: 'C5H10N2O3' },
    { name: 'Histidine', smiles: 'c1c[nH]c(n1)C[C@H](C(=O)O)N', formula: 'C6H9N3O2' },
    { name: 'Lysine', smiles: 'C(C[C@H](C(=O)O)N)CCN', formula: 'C6H14N2O2' },
    { name: 'Arginine', smiles: 'C(C[C@H](C(=O)O)N)CN=C(N)N', formula: 'C6H14N4O2' },
    { name: 'Serine', smiles: 'C([C@H](C(=O)O)N)O', formula: 'C3H7NO3' },
    { name: 'Threonine', smiles: 'C[C@H]([C@H](C(=O)O)N)O', formula: 'C4H9NO3' },
    { name: 'Cysteine', smiles: 'C([C@H](C(=O)O)N)S', formula: 'C3H7NO2S' },
    { name: 'Methionine', smiles: 'CSCC[C@H](C(=O)O)N', formula: 'C5H11NO2S' },
    { name: 'Guanine', smiles: 'c1nc2c(n1C3C(C(C(O3)CO)O)O)n[nH]c2N', formula: 'C10H13N5O5' },
    { name: 'Adenine', smiles: 'c1nc(c2c(n1)n(cn2)C3C(C(C(O3)CO)O)O)N', formula: 'C10H13N5O4' },
    { name: 'Thymine', smiles: 'Cc1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)O)O', formula: 'C10H14N2O6' },
    { name: 'Cytosine', smiles: 'c1cn(c(=O)n(c1)N)C2C(C(C(O2)CO)O)O', formula: 'C9H13N3O5' },
    { name: 'Uracil', smiles: 'c1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)O)O', formula: 'C9H12N2O6' },
    { name: 'Melatonin', smiles: 'CC(=O)NCc1ccc2c(c1)c(c[nH]2)OC', formula: 'C13H16N2O2' },
    { name: 'Gabapentin', smiles: 'C1CCC(CC1)(CC(=O)O)CN', formula: 'C9H17NO2' },
    { name: 'Pregabalin', smiles: 'CC(C)C[C@H](CC(=O)O)CN', formula: 'C8H17NO2' },
    { name: 'Omeprazole', smiles: 'Cc1c(c(nc(n1)C)OC)CS(=O)c2[nH]c3cc(c(cc3n2)OC)C', formula: 'C17H19N3O3S' },
    { name: 'Loratadine', smiles: 'c1ccc(c(c1)Cl)C2(C(=O)N(C=C2)C(=O)OCC)c3cc[nH]n3', formula: 'C22H23ClN2O2' },
    { name: 'Cetirizine', smiles: 'c1ccc(cc1)C(c2ccccc2)N3CCN(CC3)CCOCC(=O)O', formula: 'C21H25ClN2O3' },
    { name: 'Fexofenadine', smiles: 'c1ccc(cc1)C(O)(CCCC(O)(C(=O)O)C(C)C)c2ccccc2', formula: 'C32H39NO4' },
    { name: 'Ranitidine', smiles: 'CN(C)CSCC/C=C(\\N=C/N)/[N+](=O)[O-]', formula: 'C13H22N4O3S' },
    { name: 'Cimetidine', smiles: 'CN=C(N)NCCCSc1cn(c(n1)C)C', formula: 'C10H16N6S' },
    { name: 'Famotidine', smiles: 'c1csc(c1)CSCCN=C(N)N=S(=O)(N)N', formula: 'C8H15N7O2S3' },
    { name: 'Ondansetron', smiles: 'Cc1[nH]c2c(c1)c(c(=O)n2CC3C(C(C(C3)C)C)C)C', formula: 'C18H19N3O' },
    { name: 'Acyclovir', smiles: 'c1nc(c2c(n1)n(cn2)COCCO)N', formula: 'C8H11N5O3' },
    { name: 'Valacyclovir', smiles: 'CC(C)C(=O)O[C@H](C)c1ccc(cc1)c2ccccc2', formula: 'C13H20N6O4' },
    { name: 'Zidovudine (AZT)', smiles: 'c1cn(c(=O)[nH]c1=O)C2C(C(C(O2)CO)N=[N+]=[N-])O', formula: 'C10H13N5O4' },
    { name: 'Efavirenz', smiles: 'c1cc(c(cc1C(F)(F)F)C#CC2(C(=O)NC(=O)N2)c3cyclopropyl)Cl', formula: 'C14H9ClF3N2O2' },
    { name: 'Nevirapine', smiles: 'c1ccc2c(c1)c(nc(n2)c3cc(c(c(c3)C)C)C)N', formula: 'C15H14N4' },
    { name: 'Ritonavir', smiles: 'CC(C)c1nc(sc1)CNC(=O)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@@H]([C@H](C)C)O', formula: 'C37H48N6O5S2' },
    { name: 'Lopinavir', smiles: 'CC(C)c1nc(sc1)CNC(=O)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@@H]([C@H](C)C)O', formula: 'C37H48N6O5S2' },
    { name: 'Saquinavir', smiles: 'CC(C)(C)NC(=O)[C@H]1C[C@H]([C@@H](C1)O)N2C[C@H](C[C@H]2C(=O)N[C@@H](Cc3ccccc3)C[C@H]4CC[C@H]([C@@H]4)N)O', formula: 'C38H50N6O5' },
    { name: 'Indinavir', smiles: 'CC(C)(C)NC(=O)[C@H]1C[C@H]([C@@H](C1)O)N2C[C@H](C[C@H]2C(=O)N[C@@H](Cc3ccccc3)C[C@H]4CC[C@H]([C@@H]4)N)O', formula: 'C36H47N5O4' },
    { name: 'Nelfinavir', smiles: 'c1ccc(cc1)CS(=O)(=O)N[C@@H]2C[C@H]([C@@H]([C@H](C2)O)N(C)C(=O)N[C@@H](Cc3ccccc3)C[C@H]4CC[C@H]([C@@H]4)N)O', formula: 'C32H45N3O4S' },
    { name: 'Amprenavir', smiles: 'c1ccc(cc1)S(=O)(=O)N[C@H]2CCOC2', formula: 'C25H35N3O6S' },
    { name: 'Fosamprenavir', smiles: 'c1ccc(cc1)S(=O)(=O)N[C@H]2CCOC2.OP(=O)(O)O', formula: 'C25H36N3O9PS' },
    { name: 'Tipranavir', smiles: 'CC(C)c1cc(c(c(c1)S(=O)(=O)N)C(C)C)C(=O)N[C@H](Cc2ccccc2)c3cc(c(c(c3)C)C)C', formula: 'C31H33F2N3O5S' },
    { name: 'Darunavir', smiles: 'CC(C)c1nc(sc1)COC(=O)N[C@H](Cc2ccccc2)[C@H]([C@H](O)[C@@H]3CCCN3C(=O)C(C)(C)C)O', formula: 'C27H37N3O7S' },
    { name: 'Atazanavir', smiles: 'CC(C)(C)NC(=O)[C@H](c1ccccc1)N(C)C(=O)N[C@@H](Cc2ccccc2)[C@@H]([C@H](O)c3ccc(cc3)C(=O)N(C)C)O', formula: 'C38H52N6O7' },
    { name: 'Cobicistat', smiles: 'CC(C)N(C(=O)N[C@H](Cc1ccccc1)C[C@H](c2ccccc2)N(C)C(=O)N3C[C@H](C[C@H]3c4cncs4)C(C)(C)C)C', formula: 'C40H53N7O5S2' },
    { name: 'Dolutegravir', smiles: 'c1c(c(c(c(c1F)F)C(=O)N)C(=O)O)C(=O)NCC2COC(O2)c3cc(c(cc3F)F)F', formula: 'C20H19F2N3O5' },
    { name: 'Elvitegravir', smiles: 'c1c(c(c(c(c1)OC)C(=O)N)C(=O)O)C(=O)Cc2cc(c(cc2Cl)OC)OC', formula: 'C23H23ClNO7' },
    { name: 'Raltegravir', smiles: 'c1c(c(c(c(c1)F)C(=O)N)C(=O)O)C(=O)NCc2c(c(c(=O)[nH]c2=O)N)C(C)C', formula: 'C20H21FN6O5' },
    { name: 'Bictegravir', smiles: 'c1c(c(c(c(c1)F)C(=O)N)C(=O)O)C(=O)NCc2c(c(c(nc2F)C)C)C', formula: 'C21H21F3N3O5' },
    { name: 'Maraviroc', smiles: 'CC(C)N1CC(C(C1)(c2ccc(cc2)F)c3ccccc3)N4C[C@@H](C[C@@H]4C(=O)N)c5cn(c(n5)C)C', formula: 'C29H41F2N5O' },
    { name: 'Enfuvirtide', smiles: 'Ac-YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF-NH2', formula: 'C204H301N51O64' },
    { name: 'Sofosbuvir', smiles: 'C[C@H](C(=O)O[C@H]1C[C@H]([C@@H]([C@H]1C)F)n2ccc(nc2)C(=O)N)P(=O)(O)Oc3ccccc3', formula: 'C22H29FN3O9P' },
    { name: 'Ledipasvir', smiles: 'c1cc(ccc1C2=C[C@H]3N(C2=O)[C@@H](C(=O)N[C@H](C(=O)O)C(C)C)C[C@H]3c4ccc(cc4)c5ccccc5)c6nc7c(c(n6)C)c(c(c(c7)C)C)C', formula: 'C49H54F2N8O6' },
    { name: 'Dasabuvir', smiles: 'c1c(c(c(c(c1)OC)C(=O)N)C(=O)O)c2ccc(cc2)S(=O)(=O)NC(C)C', formula: 'C26H27N3O5S' },
    { name: 'Ombitasvir', smiles: 'CC(C)c1nc(sc1)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@H]([C@@H](C)C)Oc4ccc(cc4)C(=O)N(C)C', formula: 'C50H67N7O5S2' },
    { name: 'Paritaprevir', smiles: 'CC(C)c1nc(sc1)C(=O)N[C@H](C[C@H]2CCNC2=O)[C@H](c3cyclopropyl)C(=O)N[C@H](C(=O)N4C[C@H](C[C@H]4c5cncs5)C(C)(C)C)C(C)C', formula: 'C48H61N7O8S2' },
    { name: 'Glecaprevir', smiles: 'CC(C)c1nc(sc1)C(=O)N[C@H](C[C@H]2CCNC2=O)[C@H](c3cyclopropyl)C(=O)N[C@H](C(=O)N4C[C@H](C[C@H]4c5cncs5)C(C)(C)C)C(C)C', formula: 'C38H46F2N6O9S2' },
    { name: 'Pibrentasvir', smiles: 'CC(C)c1nc(sc1)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@H]([C@@H](C)C)Oc4ccc(cc4)C(=O)N(C)C', formula: 'C50H67N7O5S2' },
    { name: 'Velpatasvir', smiles: 'CC(C)c1nc(sc1)[C@H](c2ccccc2)N(C)C(=O)N[C@@H](Cc3ccccc3)[C@H]([C@@H](C)C)Oc4ccc(cc4)C(=O)N(C)C', formula: 'C49H54N8O8' },
    { name: 'Voxilaprevir', smiles: 'CC(C)c1nc(sc1)C(=O)N[C@H](C[C@H]2CCNC2=O)[C@H](c3cyclopropyl)C(=O)N[C@H](C(=O)N4C[C@H](C[C@H]4c5cncs5)C(C)(C)C)C(C)C', formula: 'C48H61N7O8S2' }
];
