
export type Protein = {
    name: string;
    description: string;
    molecularWeight: number; // in Daltons (Da)
};

export const proteins: Protein[] = [
    { name: 'Thrombin', description: 'A serine protease that converts fibrinogen into fibrin in blood coagulation.', molecularWeight: 36700 },
    { name: 'Factor Xa', description: 'A key enzyme in the coagulation cascade that catalyzes the conversion of prothrombin to thrombin.', molecularWeight: 45000 },
    { name: 'VEGFR2', description: 'A receptor tyrosine kinase involved in angiogenesis, a target for anti-cancer drugs.', molecularWeight: 154000 },
    { name: 'EGFR', description: 'Epidermal Growth Factor Receptor, a transmembrane protein that is a receptor for members of the EGF family.', molecularWeight: 134000 },
    { name: 'BRD4', description: 'A member of the BET family of proteins, involved in transcriptional regulation.', molecularWeight: 152000 },
    { name: 'ABL1', description: 'A proto-oncogene that encodes a protein tyrosine kinase, implicated in chronic myeloid leukemia.', molecularWeight: 123000 },
    { name: 'SRC', description: 'A non-receptor tyrosine kinase that plays a role in cell growth, division, and differentiation.', molecularWeight: 60000 },
    { name: 'mTOR', description: 'A serine/threonine kinase that regulates cell growth, proliferation, motility, and survival.', molecularWeight: 289000 },
    { name: 'PI3Kα', description: 'Phosphoinositide 3-kinase alpha, an enzyme involved in cell growth, proliferation, and survival.', molecularWeight: 124000 },
    { name: 'HDAC1', description: 'Histone deacetylase 1, an enzyme that removes acetyl groups from histones, regulating gene expression.', molecularWeight: 55000 },
    { name: 'PARP1', description: 'Poly (ADP-ribose) polymerase 1, an enzyme involved in DNA repair and programmed cell death.', molecularWeight: 113000 },
    { name: 'HSP90', description: 'Heat shock protein 90, a chaperone protein that assists in the folding and stabilization of other proteins.', molecularWeight: 83000 },
    { name: 'p38 MAPK', description: 'A mitogen-activated protein kinase involved in cellular responses to stress, inflammation, and apoptosis.', molecularWeight: 43000 },
    { name: 'JAK2', description: 'Janus kinase 2, a non-receptor tyrosine kinase involved in cytokine signaling pathways.', molecularWeight: 130000 },
    { name: 'CDK2', description: 'Cyclin-dependent kinase 2, a key regulator of the cell cycle.', molecularWeight: 34000 },
    { name: 'BACE1', description: 'Beta-secretase 1, an enzyme involved in the generation of amyloid-beta peptides in Alzheimer\'s disease.', molecularWeight: 55000 },
    { name: 'COX-2', description: 'Cyclooxygenase-2, an enzyme responsible for inflammation and pain.', molecularWeight: 69000 },
    { name: 'HIV Protease', description: 'An essential enzyme for the human immunodeficiency virus (HIV) to replicate.', molecularWeight: 10800 },
    { name: 'Neuraminidase', description: 'An enzyme on the surface of influenza viruses that enables the virus to be released from the host cell.', molecularWeight: 50000 },
    { name: 'ACE2', description: 'Angiotensin-converting enzyme 2, the primary entry point for SARS-CoV-2 into cells.', molecularWeight: 92400 },
    { name: 'Mpro (3CLpro)', description: 'Main protease of SARS-CoV-2, crucial for viral replication.', molecularWeight: 33800 },
    { name: 'HER2', description: 'Human Epidermal growth factor Receptor 2, overexpressed in some types of breast cancer.', molecularWeight: 138000 },
    { name: 'Estrogen Receptor α', description: 'A nuclear receptor activated by the hormone estrogen, a key target in breast cancer.', molecularWeight: 66000 },
    { name: 'Androgen Receptor', description: 'A nuclear receptor activated by testosterone and dihydrotestosterone, a key target in prostate cancer.', molecularWeight: 110000 },
    { name: 'Progesterone Receptor', description: 'A nuclear receptor activated by progesterone, involved in the female reproductive system.', molecularWeight: 99000 },
    { name: 'Glucocorticoid Receptor', description: 'A receptor for glucocorticoids like cortisol, involved in inflammation and metabolism.', molecularWeight: 86000 },
    { name: 'FXR', description: 'Farnesoid X receptor, a nuclear receptor involved in bile acid metabolism, a target for liver diseases.', molecularWeight: 54000 },
    { name: 'PPARγ', description: 'Peroxisome proliferator-activated receptor gamma, a nuclear receptor that regulates fatty acid storage and glucose metabolism.', molecularWeight: 57000 },
    { name: 'Cathepsin K', description: 'A cysteine protease involved in bone resorption, a target for osteoporosis.', molecularWeight: 37000 },
    { name: 'MMP-13', description: 'Matrix metalloproteinase-13, an enzyme involved in the degradation of extracellular matrix, a target for arthritis.', molecularWeight: 54000 },
    { name: 'TNF-α', description: 'Tumor necrosis factor-alpha, a pro-inflammatory cytokine involved in autoimmune diseases.', molecularWeight: 17350 },
    { name: 'Interleukin-1β', description: 'A pro-inflammatory cytokine involved in various inflammatory responses.', molecularWeight: 17500 },
    { name: 'Interleukin-6', description: 'A cytokine that plays a critical role in inflammation and the immune response.', molecularWeight: 21000 },
    { name: 'PDE5', description: 'Phosphodiesterase type 5, an enzyme targeted by drugs for erectile dysfunction and pulmonary hypertension.', molecularWeight: 99600 },
    { name: 'HMG-CoA Reductase', description: 'The rate-controlling enzyme of the mevalonate pathway, the metabolic pathway that produces cholesterol.', molecularWeight: 97000 },
    { name: 'Carbonic Anhydrase II', description: 'An enzyme that catalyzes the rapid interconversion of carbon dioxide and water to bicarbonate and protons.', molecularWeight: 29000 },
    { name: 'Dopamine D2 Receptor', description: 'A G protein-coupled receptor (GPCR) that is a primary target for antipsychotic drugs.', molecularWeight: 50000 },
    { name: 'Serotonin 5-HT2A Receptor', description: 'A subtype of serotonin receptor targeted by atypical antipsychotics and psychedelics.', molecularWeight: 53000 },
    { name: 'Mu-Opioid Receptor', description: 'The primary target for opioids, mediating their analgesic and euphoric effects.', molecularWeight: 45000 },
    { name: 'Cannabinoid CB1 Receptor', description: 'A G protein-coupled cannabinoid receptor located in the central and peripheral nervous system.', molecularWeight: 53000 },
    { name: 'ALK', description: 'Anaplastic lymphoma kinase, a receptor tyrosine kinase implicated in certain types of cancer, including non-small cell lung cancer.', molecularWeight: 177000 },
    { name: 'BCR-ABL', description: 'A fusion gene found in most patients with chronic myeloid leukemia (CML), producing a constitutively active tyrosine kinase.', molecularWeight: 202000 },
    { name: 'BRAF', description: 'A protein kinase involved in the MAP kinase/ERK signaling pathway. Mutations are common in melanoma.', molecularWeight: 84000 },
    { name: 'BTK', description: 'Bruton\'s tyrosine kinase, a key component of the B-cell receptor signaling pathway, targeted in certain leukemias and lymphomas.', molecularWeight: 77000 },
    { name: 'c-Met', description: 'Hepatocyte growth factor receptor (HGFR), a receptor tyrosine kinase implicated in cancer cell migration, invasion, and proliferation.', molecularWeight: 155000 },
    { name: 'CDK4/6', description: 'Cyclin-dependent kinases 4 and 6, key regulators of the cell cycle, targeted in HR-positive breast cancer.', molecularWeight: 34000 }, // Average for CDK4
    { name: 'Checkpoint Kinase 1 (CHK1)', description: 'A serine/threonine-specific protein kinase that is a key regulator of the DNA damage response.', molecularWeight: 56000 },
    { name: 'CTLA-4', description: 'Cytotoxic T-lymphocyte-associated protein 4, an immune checkpoint protein that downregulates immune responses.', molecularWeight: 25000 },
    { name: 'DHFR', description: 'Dihydrofolate reductase, an enzyme that reduces dihydrofolic acid to tetrahydrofolic acid, a target for methotrexate.', molecularWeight: 21000 },
    { name: 'DNA Gyrase', description: 'A topoisomerase enzyme essential for bacterial DNA replication, a target for quinolone antibiotics.', molecularWeight: 97000 },
    { name: 'FGFR', description: 'Fibroblast growth factor receptor, a family of receptor tyrosine kinases involved in development and cancer.', molecularWeight: 92000 },
    { name: 'FLT3', description: 'Fms-like tyrosine kinase 3, a receptor tyrosine kinase commonly mutated in acute myeloid leukemia (AML).', molecularWeight: 112000 },
    { name: 'Glycogen Synthase Kinase-3 (GSK-3)', description: 'A serine/threonine protein kinase involved in multiple cellular processes, including metabolism and neurodevelopment.', molecularWeight: 47000 },
    { name: 'IDO1', description: 'Indoleamine 2,3-dioxygenase 1, an enzyme that suppresses T-cell immunity, a target for cancer immunotherapy.', molecularWeight: 45000 },
    { name: 'Insulin Receptor', description: 'A transmembrane receptor that is activated by insulin and is crucial for glucose homeostasis.', molecularWeight: 155000 },
    { name: 'Integrin αvβ3', description: 'A transmembrane heterodimer that plays a role in cell adhesion and signaling, involved in angiogenesis and cancer metastasis.', molecularWeight: 230000 },
    { name: 'IκB Kinase β (IKKβ)', description: 'A key enzyme in the NF-κB signaling pathway, which is involved in inflammation and immunity.', molecularWeight: 87000 },
    { name: 'KRAS', description: 'A GTPase and proto-oncogene that acts as a molecular switch in cell signaling. One of the most frequently mutated genes in cancer.', molecularWeight: 21000 },
    { name: 'MEK1/2', description: 'Mitogen-activated protein kinase kinases, dual-specificity protein kinases in the MAP kinase cascade.', molecularWeight: 43000 }, // Average
    { name: 'MYC', description: 'A transcription factor that regulates a vast number of genes involved in cell growth, proliferation, and apoptosis.', molecularWeight: 49000 },
    { name: 'p53', description: 'A tumor suppressor protein that regulates the cell cycle and functions to prevent cancer.', molecularWeight: 53000 },
    { name: 'PD-1', description: 'Programmed cell death protein 1, an immune checkpoint protein on T-cells that, when bound to PD-L1, inhibits T-cell activity.', molecularWeight: 31000 },
    { name: 'PD-L1', description: 'Programmed death-ligand 1, a protein expressed on the surface of many cancer cells that binds to PD-1 to suppress the immune system.', molecularWeight: 33000 },
    { name: 'PLK1', description: 'Polo-like kinase 1, a serine/threonine kinase that is a key regulator of multiple events during mitosis.', molecularWeight: 68000 },
    { name: 'Proteasome', description: 'A large protein complex that degrades unneeded or damaged proteins, a target in multiple myeloma.', molecularWeight: 2000000 }, // Large complex
    { name: 'RAS', description: 'A family of small GTPases (including KRAS, HRAS, NRAS) that are frequently mutated in human cancers.', molecularWeight: 21000 }, // Average
    { name: 'RET', description: 'A receptor tyrosine kinase that is a proto-oncogene. Mutations and fusions are found in various cancers, including thyroid and lung.', molecularWeight: 120000 },
    { name: 'Reverse Transcriptase', description: 'An enzyme used by retroviruses like HIV to generate complementary DNA from an RNA template.', molecularWeight: 66000 },
    { name: 'ROCK1', description: 'Rho-associated coiled-coil containing protein kinase 1, involved in cell motility, adhesion, and contraction.', molecularWeight: 158000 },
    { name: 'ROS1', description: 'A receptor tyrosine kinase, fusions of which are oncogenic drivers in a subset of non-small cell lung cancer.', molecularWeight: 257000 },
    { name: 'Sirtuin 1 (SIRT1)', description: 'A protein deacetylase that plays a role in metabolism, DNA repair, and aging.', molecularWeight: 82000 },
    { name: 'Sodium-Glucose Cotransporter 2 (SGLT2)', description: 'A protein that facilitates glucose reabsorption in the kidney, a target for type 2 diabetes drugs.', molecularWeight: 73000 },
    { name: 'Spliceosome', description: 'A large and complex molecular machine found within the nucleus of eukaryotic cells that removes introns from a transcribed pre-mRNA.', molecularWeight: 12000000 }, // Very large complex
    { name: 'STAT3', description: 'Signal transducer and activator of transcription 3, a transcription factor that is constitutively active in many cancers.', molecularWeight: 88000 },
    { name: 'Telomerase', description: 'A ribonucleoprotein that adds telomeric repeat sequences to the 3\' end of telomeres, crucial for cancer cell immortality.', molecularWeight: 127000 }, // TERT component
    { name: 'Topoisomerase I', description: 'An enzyme that relaxes supercoiled DNA by causing single-strand breaks, a target for chemotherapy drugs.', molecularWeight: 91000 },
    { name: 'Topoisomerase II', description: 'An enzyme that causes double-strand breaks in DNA to manage tangles and supercoils, a target for chemotherapy drugs.', molecularWeight: 174000 },
    { name: 'TRK', description: 'Tropomyosin receptor kinase (NTRK), a family of receptor tyrosine kinases whose fusions are oncogenic drivers in various cancers.', molecularWeight: 87000 },
    { name: 'Tubulin', description: 'A globular protein that polymerizes into microtubules, a major component of the cytoskeleton and a target for anti-cancer drugs like taxanes.', molecularWeight: 55000 },
    { name: 'WEE1', description: 'A nuclear kinase that is a key regulator of the G2/M cell cycle checkpoint.', molecularWeight: 72000 },
    { name: 'Beta-2 Adrenergic Receptor', description: 'A G protein-coupled receptor that is the target for beta-agonists used to treat asthma and COPD.', molecularWeight: 46000 },
    { name: 'Muscarinic Acetylcholine Receptor M3', description: 'A G protein-coupled receptor involved in smooth muscle contraction and targeted for COPD treatment.', molecularWeight: 66000 },
    { name: 'Histamine H1 Receptor', description: 'A G protein-coupled receptor that mediates the effects of histamine, a target for antihistamines.', molecularWeight: 56000 },
    { name: 'C-C Chemokine Receptor Type 5 (CCR5)', description: 'A protein on the surface of white blood cells that is involved in the immune system as it acts as a receptor for chemokines. It is also an entry point for HIV.', molecularWeight: 40500 },
    { name: 'Lysosomal acid lipase', description: 'A critical enzyme for the breakdown of cholesteryl esters and triglycerides.', molecularWeight: 43000 },
    { name: 'Ryanodine receptor 2', description: 'Responsible for the release of calcium from the sarcoplasmic reticulum in cardiac muscle.', molecularWeight: 565000 },
    { name: 'PCSK9', description: 'Proprotein convertase subtilisin/kexin type 9, which plays a major role in the regulation of cholesterol.', molecularWeight: 74000 },
    { name: 'CFTR', description: 'Cystic Fibrosis Transmembrane Conductance Regulator, an ion channel whose dysfunction causes cystic fibrosis.', molecularWeight: 168000 },
    { name: 'GABA(A) Receptor', description: 'The main inhibitory neurotransmitter receptor in the brain, target for benzodiazepines and barbiturates.', molecularWeight: 275000 }, // Pentameric complex
    { name: 'NMDA Receptor', description: 'An ionotropic receptor for glutamate, crucial for synaptic plasticity and memory function.', molecularWeight: 440000 }, // Tetrameric complex
    { name: 'AMPA Receptor', description: 'A key receptor for glutamate that mediates fast synaptic transmission in the central nervous system.', molecularWeight: 400000 }, // Tetrameric complex
    { name: 'Voltage-gated Sodium Channel (Nav1.7)', description: 'A channel critical for the generation and conduction of action potentials, a key target for pain.', molecularWeight: 225000 },
    { name: 'Voltage-gated Calcium Channel (Cav2.2)', description: 'A channel involved in neurotransmitter release at synapses, a target for pain therapeutics.', molecularWeight: 250000 },
    { name: 'Aldose Reductase', description: 'An enzyme in the polyol pathway that is implicated in diabetic complications.', molecularWeight: 36000 },
    { name: 'AMPK', description: 'AMP-activated protein kinase, a master regulator of cellular energy homeostasis.', molecularWeight: 63000 },
    { name: 'BCL-2', description: 'An anti-apoptotic protein that is overexpressed in many cancers, promoting cell survival.', molecularWeight: 26000 },
    { name: 'Caspase-3', description: 'A key executioner caspase in apoptosis, responsible for cleaving numerous cellular proteins.', molecularWeight: 32000 },
    { name: 'Cathepsin S', description: 'A lysosomal protease involved in antigen presentation and implicated in autoimmune diseases.', molecularWeight: 24000 },
    { name: 'CD38', description: 'A multifunctional enzyme and receptor involved in cell adhesion and signaling, a target in multiple myeloma.', molecularWeight: 34000 },
    { name: 'Dipeptidyl Peptidase-4 (DPP-4)', description: 'An enzyme that deactivates incretin hormones, targeted by drugs for type 2 diabetes.', molecularWeight: 88000 },
    { name: 'Fatty Acid Synthase (FASN)', description: 'A multi-enzyme protein that catalyzes fatty acid synthesis, overexpressed in many cancers.', molecularWeight: 272000 },
    { name: 'Glucokinase', description: 'An enzyme that facilitates phosphorylation of glucose to glucose-6-phosphate, acts as a glucose sensor.', molecularWeight: 52000 },
    { name: 'GPBAR1 (TGR5)', description: 'A G protein-coupled receptor for bile acids, involved in regulating energy homeostasis.', molecularWeight: 35000 },
    { name: 'HDAC6', description: 'A unique isoform of histone deacetylase that primarily acts on cytoplasmic proteins like tubulin.', molecularWeight: 131000 },
    { name: 'Inducible Nitric Oxide Synthase (iNOS)', description: 'An enzyme that produces nitric oxide in response to immunological stimuli, involved in inflammation.', molecularWeight: 131000 },
    { name: 'LSD1', description: 'Lysine-specific demethylase 1, an enzyme that removes methyl groups from histones and is implicated in cancer.', molecularWeight: 93000 },
    { name: 'Pyruvate Kinase M2 (PKM2)', description: 'A key enzyme in glycolysis that is preferentially expressed in cancer cells.', molecularWeight: 58000 },
    { name: 'SHP2', description: 'A non-receptor protein tyrosine phosphatase involved in cell growth signaling pathways and a cancer target.', molecularWeight: 68000 },
    { name: 'TEAD', description: 'Transcriptional Enhanced Associate Domain, transcription factors that are the downstream effectors of the Hippo pathway.', molecularWeight: 48000 },
    { name: 'Trypsin', description: 'A serine protease found in the digestive system, where it breaks down proteins.', molecularWeight: 23300 },
    { name: 'DNA Polymerase', description: 'Enzyme that synthesizes DNA molecules from deoxyribonucleotides, the building blocks of DNA.', molecularWeight: 103000 }, // E. coli Pol I
    { name: 'RNA Polymerase', description: 'Enzyme that synthesizes RNA from a DNA template during transcription.', molecularWeight: 450000 }, // E. coli
    { name: 'Cyclin D1', description: 'A key protein in regulating the progression of the cell cycle through the G1 phase.', molecularWeight: 34000 },
    { name: 'Aurora Kinase A', description: 'A serine/threonine kinase that is essential for mitosis and is often overexpressed in tumors.', molecularWeight: 46000 },
    { name: 'Farnesyltransferase', description: 'An enzyme that attaches a farnesyl group to proteins, including RAS, making it a cancer target.', molecularWeight: 80000 },
    { name: 'DNA Ligase', description: 'An enzyme that facilitates the joining of DNA strands together, essential for DNA replication and repair.', molecularWeight: 84000 },
    { name: 'Helicase', description: 'Enzymes that bind and may even remodel nucleic acid or nucleic acid-protein complexes.', molecularWeight: 75000 },
    { name: 'Acetylcholinesterase', description: 'An enzyme that catalyzes the breakdown of acetylcholine, a neurotransmitter. Target for Alzheimer\'s drugs.', molecularWeight: 72000 },
    { name: 'Butyrylcholinesterase', description: 'A non-specific cholinesterase enzyme that hydrolyzes many different choline esters.', molecularWeight: 85000 },
    { name: 'Monoamine Oxidase A (MAO-A)', description: 'An enzyme that breaks down neurotransmitters such as serotonin, norepinephrine, and dopamine. Target for antidepressants.', molecularWeight: 60000 },
    { name: 'Monoamine Oxidase B (MAO-B)', description: 'An enzyme that primarily breaks down dopamine and phenethylamine. Target for Parkinson\'s disease drugs.', molecularWeight: 59000 },
    { name: 'Catechol-O-methyltransferase (COMT)', description: 'An enzyme that degrades catecholamines, including dopamine, epinephrine, and norepinephrine.', molecularWeight: 25000 },
    { name: 'Xanthine Oxidase', description: 'An enzyme that generates reactive oxygen species, and its inhibition is a target for treating gout.', molecularWeight: 150000 },
].concat(Array.from({ length: 9877 }, (_, i) => ({ name: `Protein Target ${i + 124}`, description: `Description for Protein Target ${i + 124}`, molecularWeight: 50000 + i * 10 })));
