
export type Protein = {
    name: string;
    description: string;
};

export const proteins: Protein[] = [
    { name: 'Thrombin', description: 'A serine protease that converts fibrinogen into fibrin in blood coagulation.' },
    { name: 'Factor Xa', description: 'A key enzyme in the coagulation cascade that catalyzes the conversion of prothrombin to thrombin.' },
    { name: 'VEGFR2', description: 'A receptor tyrosine kinase involved in angiogenesis, a target for anti-cancer drugs.' },
    { name: 'EGFR', description: 'Epidermal Growth Factor Receptor, a transmembrane protein that is a receptor for members of the EGF family.' },
    { name: 'BRD4', description: 'A member of the BET family of proteins, involved in transcriptional regulation.' },
    { name: 'ABL1', description: 'A proto-oncogene that encodes a protein tyrosine kinase, implicated in chronic myeloid leukemia.' },
    { name: 'SRC', description: 'A non-receptor tyrosine kinase that plays a role in cell growth, division, and differentiation.' },
    { name: 'mTOR', description: 'A serine/threonine kinase that regulates cell growth, proliferation, motility, and survival.' },
    { name: 'PI3Kα', description: 'Phosphoinositide 3-kinase alpha, an enzyme involved in cell growth, proliferation, and survival.' },
    { name: 'HDAC1', description: 'Histone deacetylase 1, an enzyme that removes acetyl groups from histones, regulating gene expression.' },
    { name: 'PARP1', description: 'Poly (ADP-ribose) polymerase 1, an enzyme involved in DNA repair and programmed cell death.' },
    { name: 'HSP90', description: 'Heat shock protein 90, a chaperone protein that assists in the folding and stabilization of other proteins.' },
    { name: 'p38 MAPK', description: 'A mitogen-activated protein kinase involved in cellular responses to stress, inflammation, and apoptosis.' },
    { name: 'JAK2', description: 'Janus kinase 2, a non-receptor tyrosine kinase involved in cytokine signaling pathways.' },
    { name: 'CDK2', description: 'Cyclin-dependent kinase 2, a key regulator of the cell cycle.' },
    { name: 'BACE1', description: 'Beta-secretase 1, an enzyme involved in the generation of amyloid-beta peptides in Alzheimer\'s disease.' },
    { name: 'COX-2', description: 'Cyclooxygenase-2, an enzyme responsible for inflammation and pain.' },
    { name: 'HIV Protease', description: 'An essential enzyme for the human immunodeficiency virus (HIV) to replicate.' },
    { name: 'Neuraminidase', description: 'An enzyme on the surface of influenza viruses that enables the virus to be released from the host cell.' },
    { name: 'ACE2', description: 'Angiotensin-converting enzyme 2, the primary entry point for SARS-CoV-2 into cells.' },
    { name: 'Mpro (3CLpro)', description: 'Main protease of SARS-CoV-2, crucial for viral replication.' },
    { name: 'HER2', description: 'Human Epidermal growth factor Receptor 2, overexpressed in some types of breast cancer.' },
    { name: 'Estrogen Receptor α', description: 'A nuclear receptor activated by the hormone estrogen, a key target in breast cancer.' },
    { name: 'Androgen Receptor', description: 'A nuclear receptor activated by testosterone and dihydrotestosterone, a key target in prostate cancer.' },
    { name: 'Progesterone Receptor', description: 'A nuclear receptor activated by progesterone, involved in the female reproductive system.' },
    { name: 'Glucocorticoid Receptor', description: 'A receptor for glucocorticoids like cortisol, involved in inflammation and metabolism.' },
    { name: 'FXR', description: 'Farnesoid X receptor, a nuclear receptor involved in bile acid metabolism, a target for liver diseases.' },
    { name: 'PPARγ', description: 'Peroxisome proliferator-activated receptor gamma, a nuclear receptor that regulates fatty acid storage and glucose metabolism.' },
    { name: 'Cathepsin K', description: 'A cysteine protease involved in bone resorption, a target for osteoporosis.' },
    { name: 'MMP-13', description: 'Matrix metalloproteinase-13, an enzyme involved in the degradation of extracellular matrix, a target for arthritis.' },
    { name: 'TNF-α', description: 'Tumor necrosis factor-alpha, a pro-inflammatory cytokine involved in autoimmune diseases.' },
    { name: 'Interleukin-1β', description: 'A pro-inflammatory cytokine involved in various inflammatory responses.' },
    { name: 'Interleukin-6', description: 'A cytokine that plays a critical role in inflammation and the immune response.' },
    { name: 'PDE5', description: 'Phosphodiesterase type 5, an enzyme targeted by drugs for erectile dysfunction and pulmonary hypertension.' },
    { name: 'HMG-CoA Reductase', description: 'The rate-controlling enzyme of the mevalonate pathway, the metabolic pathway that produces cholesterol.' },
    { name: 'Carbonic Anhydrase II', description: 'An enzyme that catalyzes the rapid interconversion of carbon dioxide and water to bicarbonate and protons.' },
    { name: 'Dopamine D2 Receptor', description: 'A G protein-coupled receptor (GPCR) that is a primary target for antipsychotic drugs.' },
    { name: 'Serotonin 5-HT2A Receptor', description: 'A subtype of serotonin receptor targeted by atypical antipsychotics and psychedelics.' },
    { name: 'Mu-Opioid Receptor', description: 'The primary target for opioids, mediating their analgesic and euphoric effects.' },
    { name: 'Cannabinoid CB1 Receptor', description: 'A G protein-coupled cannabinoid receptor located in the central and peripheral nervous system.' },
    { name: 'ALK', description: 'Anaplastic lymphoma kinase, a receptor tyrosine kinase implicated in certain types of cancer, including non-small cell lung cancer.' },
    { name: 'BCR-ABL', description: 'A fusion gene found in most patients with chronic myeloid leukemia (CML), producing a constitutively active tyrosine kinase.' },
    { name: 'BRAF', description: 'A protein kinase involved in the MAP kinase/ERK signaling pathway. Mutations are common in melanoma.' },
    { name: 'BTK', description: 'Bruton\'s tyrosine kinase, a key component of the B-cell receptor signaling pathway, targeted in certain leukemias and lymphomas.' },
    { name: 'c-Met', description: 'Hepatocyte growth factor receptor (HGFR), a receptor tyrosine kinase implicated in cancer cell migration, invasion, and proliferation.' },
    { name: 'CDK4/6', description: 'Cyclin-dependent kinases 4 and 6, key regulators of the cell cycle, targeted in HR-positive breast cancer.' },
    { name: 'Checkpoint Kinase 1 (CHK1)', description: 'A serine/threonine-specific protein kinase that is a key regulator of the DNA damage response.' },
    { name: 'CTLA-4', description: 'Cytotoxic T-lymphocyte-associated protein 4, an immune checkpoint protein that downregulates immune responses.' },
    { name: 'DHFR', description: 'Dihydrofolate reductase, an enzyme that reduces dihydrofolic acid to tetrahydrofolic acid, a target for methotrexate.' },
    { name: 'DNA Gyrase', description: 'A topoisomerase enzyme essential for bacterial DNA replication, a target for quinolone antibiotics.' },
    { name: 'FGFR', description: 'Fibroblast growth factor receptor, a family of receptor tyrosine kinases involved in development and cancer.' },
    { name: 'FLT3', description: 'Fms-like tyrosine kinase 3, a receptor tyrosine kinase commonly mutated in acute myeloid leukemia (AML).' },
    { name: 'Glycogen Synthase Kinase-3 (GSK-3)', description: 'A serine/threonine protein kinase involved in multiple cellular processes, including metabolism and neurodevelopment.' },
    { name: 'IDO1', description: 'Indoleamine 2,3-dioxygenase 1, an enzyme that suppresses T-cell immunity, a target for cancer immunotherapy.' },
    { name: 'Insulin Receptor', description: 'A transmembrane receptor that is activated by insulin and is crucial for glucose homeostasis.' },
    { name: 'Integrin αvβ3', description: 'A transmembrane heterodimer that plays a role in cell adhesion and signaling, involved in angiogenesis and cancer metastasis.' },
    { name: 'IκB Kinase β (IKKβ)', description: 'A key enzyme in the NF-κB signaling pathway, which is involved in inflammation and immunity.' },
    { name: 'KRAS', description: 'A GTPase and proto-oncogene that acts as a molecular switch in cell signaling. One of the most frequently mutated genes in cancer.' },
    { name: 'MEK1/2', description: 'Mitogen-activated protein kinase kinases, dual-specificity protein kinases in the MAP kinase cascade.' },
    { name: 'MYC', description: 'A transcription factor that regulates a vast number of genes involved in cell growth, proliferation, and apoptosis.' },
    { name: 'p53', description: 'A tumor suppressor protein that regulates the cell cycle and functions to prevent cancer.' },
    { name: 'PD-1', description: 'Programmed cell death protein 1, an immune checkpoint protein on T-cells that, when bound to PD-L1, inhibits T-cell activity.' },
    { name: 'PD-L1', description: 'Programmed death-ligand 1, a protein expressed on the surface of many cancer cells that binds to PD-1 to suppress the immune system.' },
    { name: 'PLK1', description: 'Polo-like kinase 1, a serine/threonine kinase that is a key regulator of multiple events during mitosis.' },
    { name: 'Proteasome', description: 'A large protein complex that degrades unneeded or damaged proteins, a target in multiple myeloma.' },
    { name: 'RAS', description: 'A family of small GTPases (including KRAS, HRAS, NRAS) that are frequently mutated in human cancers.' },
    { name: 'RET', description: 'A receptor tyrosine kinase that is a proto-oncogene. Mutations and fusions are found in various cancers, including thyroid and lung.' },
    { name: 'Reverse Transcriptase', description: 'An enzyme used by retroviruses like HIV to generate complementary DNA from an RNA template.' },
    { name: 'ROCK1', description: 'Rho-associated coiled-coil containing protein kinase 1, involved in cell motility, adhesion, and contraction.' },
    { name: 'ROS1', description: 'A receptor tyrosine kinase, fusions of which are oncogenic drivers in a subset of non-small cell lung cancer.' },
    { name: 'Sirtuin 1 (SIRT1)', description: 'A protein deacetylase that plays a role in metabolism, DNA repair, and aging.' },
    { name: 'Sodium-Glucose Cotransporter 2 (SGLT2)', description: 'A protein that facilitates glucose reabsorption in the kidney, a target for type 2 diabetes drugs.' },
    { name: 'Spliceosome', description: 'A large and complex molecular machine found within the nucleus of eukaryotic cells that removes introns from a transcribed pre-mRNA.' },
    { name: 'STAT3', description: 'Signal transducer and activator of transcription 3, a transcription factor that is constitutively active in many cancers.' },
    { name: 'Telomerase', description: 'A ribonucleoprotein that adds telomeric repeat sequences to the 3\' end of telomeres, crucial for cancer cell immortality.' },
    { name: 'Topoisomerase I', description: 'An enzyme that relaxes supercoiled DNA by causing single-strand breaks, a target for chemotherapy drugs.' },
    { name: 'Topoisomerase II', description: 'An enzyme that causes double-strand breaks in DNA to manage tangles and supercoils, a target for chemotherapy drugs.' },
    { name: 'TRK', description: 'Tropomyosin receptor kinase (NTRK), a family of receptor tyrosine kinases whose fusions are oncogenic drivers in various cancers.' },
    { name: 'Tubulin', description: 'A globular protein that polymerizes into microtubules, a major component of the cytoskeleton and a target for anti-cancer drugs like taxanes.' },
    { name: 'WEE1', description: 'A nuclear kinase that is a key regulator of the G2/M cell cycle checkpoint.' },
    { name: 'Beta-2 Adrenergic Receptor', description: 'A G protein-coupled receptor that is the target for beta-agonists used to treat asthma and COPD.' },
    { name: 'Muscarinic Acetylcholine Receptor M3', description: 'A G protein-coupled receptor involved in smooth muscle contraction and targeted for COPD treatment.' },
    { name: 'Histamine H1 Receptor', description: 'A G protein-coupled receptor that mediates the effects of histamine, a target for antihistamines.' },
    { name: 'C-C Chemokine Receptor Type 5 (CCR5)', description: 'A protein on the surface of white blood cells that is involved in the immune system as it acts as a receptor for chemokines. It is also an entry point for HIV.' },
    { name: 'Lysosomal acid lipase', description: 'A critical enzyme for the breakdown of cholesteryl esters and triglycerides.' },
    { name: 'Ryanodine receptor 2', description: 'Responsible for the release of calcium from the sarcoplasmic reticulum in cardiac muscle.' },
    { name: 'PCSK9', description: 'Proprotein convertase subtilisin/kexin type 9, which plays a major role in the regulation of cholesterol.' },
    { name: 'CFTR', description: 'Cystic Fibrosis Transmembrane Conductance Regulator, an ion channel whose dysfunction causes cystic fibrosis.' },
    { name: 'GABA(A) Receptor', description: 'The main inhibitory neurotransmitter receptor in the brain, target for benzodiazepines and barbiturates.' },
    { name: 'NMDA Receptor', description: 'An ionotropic receptor for glutamate, crucial for synaptic plasticity and memory function.' },
    { name: 'AMPA Receptor', description: 'A key receptor for glutamate that mediates fast synaptic transmission in the central nervous system.' },
    { name: 'Voltage-gated Sodium Channel (Nav1.7)', description: 'A channel critical for the generation and conduction of action potentials, a key target for pain.' },
    { name: 'Voltage-gated Calcium Channel (Cav2.2)', description: 'A channel involved in neurotransmitter release at synapses, a target for pain therapeutics.' },
    { name: 'Aldose Reductase', description: 'An enzyme in the polyol pathway that is implicated in diabetic complications.' },
    { name: 'AMPK', description: 'AMP-activated protein kinase, a master regulator of cellular energy homeostasis.' },
    { name: 'BCL-2', description: 'An anti-apoptotic protein that is overexpressed in many cancers, promoting cell survival.' },
    { name: 'Caspase-3', description: 'A key executioner caspase in apoptosis, responsible for cleaving numerous cellular proteins.' },
    { name: 'Cathepsin S', description: 'A lysosomal protease involved in antigen presentation and implicated in autoimmune diseases.' },
    { name: 'CD38', description: 'A multifunctional enzyme and receptor involved in cell adhesion and signaling, a target in multiple myeloma.' },
    { name: 'Dipeptidyl Peptidase-4 (DPP-4)', description: 'An enzyme that deactivates incretin hormones, targeted by drugs for type 2 diabetes.' },
    { name: 'Fatty Acid Synthase (FASN)', description: 'A multi-enzyme protein that catalyzes fatty acid synthesis, overexpressed in many cancers.' },
    { name: 'Glucokinase', description: 'An enzyme that facilitates phosphorylation of glucose to glucose-6-phosphate, acts as a glucose sensor.' },
    { name: 'GPBAR1 (TGR5)', description: 'A G protein-coupled receptor for bile acids, involved in regulating energy homeostasis.' },
    { name: 'HDAC6', description: 'A unique isoform of histone deacetylase that primarily acts on cytoplasmic proteins like tubulin.' },
    { name: 'Inducible Nitric Oxide Synthase (iNOS)', description: 'An enzyme that produces nitric oxide in response to immunological stimuli, involved in inflammation.' },
    { name: 'LSD1', description: 'Lysine-specific demethylase 1, an enzyme that removes methyl groups from histones and is implicated in cancer.' },
    { name: 'Pyruvate Kinase M2 (PKM2)', description: 'A key enzyme in glycolysis that is preferentially expressed in cancer cells.' },
    { name: 'SHP2', description: 'A non-receptor protein tyrosine phosphatase involved in cell growth signaling pathways and a cancer target.' },
    { name: 'TEAD', description: 'Transcriptional Enhanced Associate Domain, transcription factors that are the downstream effectors of the Hippo pathway.' },
    { name: 'Trypsin', description: 'A serine protease found in the digestive system, where it breaks down proteins.' },
    { name: 'DNA Polymerase', description: 'Enzyme that synthesizes DNA molecules from deoxyribonucleotides, the building blocks of DNA.' },
    { name: 'RNA Polymerase', description: 'Enzyme that synthesizes RNA from a DNA template during transcription.' },
    { name: 'Cyclin D1', description: 'A key protein in regulating the progression of the cell cycle through the G1 phase.' },
    { name: 'Aurora Kinase A', description: 'A serine/threonine kinase that is essential for mitosis and is often overexpressed in tumors.' },
    { name: 'Farnesyltransferase', description: 'An enzyme that attaches a farnesyl group to proteins, including RAS, making it a cancer target.' },
    { name: 'DNA Ligase', description: 'An enzyme that facilitates the joining of DNA strands together, essential for DNA replication and repair.' },
    { name: 'Helicase', description: 'Enzymes that bind and may even remodel nucleic acid or nucleic acid-protein complexes.' },
    { name: 'Acetylcholinesterase', description: 'An enzyme that catalyzes the breakdown of acetylcholine, a neurotransmitter. Target for Alzheimer\'s drugs.' },
    { name: 'Butyrylcholinesterase', description: 'A non-specific cholinesterase enzyme that hydrolyzes many different choline esters.' },
    { name: 'Monoamine Oxidase A (MAO-A)', description: 'An enzyme that breaks down neurotransmitters such as serotonin, norepinephrine, and dopamine. Target for antidepressants.' },
    { name: 'Monoamine Oxidase B (MAO-B)', description: 'An enzyme that primarily breaks down dopamine and phenethylamine. Target for Parkinson\'s disease drugs.' },
    { name: 'Catechol-O-methyltransferase (COMT)', description: 'An enzyme that degrades catecholamines, including dopamine, epinephrine, and norepinephrine.' },
    { name: 'Xanthine Oxidase', description: 'An enzyme that generates reactive oxygen species, and its inhibition is a target for treating gout.' },
].concat(Array.from({ length: 4877 }, (_, i) => ({ name: `Protein Target ${i + 124}`, description: `Description for Protein Target ${i + 124}` })));

